/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import {
  AnyCollection,
  createInternalBuilder,
  BuildContext as ExternalContentCollectionsContext
} from "@content-collections/core";
import { UserConfig } from "powerlines/types/config";
import { PluginContext } from "powerlines/types/context";
import { ResolvedConfig } from "powerlines/types/resolved";

export type ContentCollectionsContext = Pick<
  Awaited<ReturnType<typeof createInternalBuilder>>,
  "build" | "on"
> & { context: ExternalContentCollectionsContext };

export interface ContentCollectionsPluginOptions {
  /**
   * The path to a custom Prisma configuration file.
   *
   * @remarks
   * This field allows the use of the "\{projectRoot\}" token to refer to the project's root directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{projectRoot\}/content-collections.ts"
   */
  configFile?: string;

  /**
   * The list of content collections to include.
   */
  collections?: AnyCollection[];

  /**
   * The path to the content collection output files generated by the plugin.
   *
   * @remarks
   * If using the default value, the file can be imported from "powerlines:content/collection-name". This field allows the use of the "\{builtinPath\}" token to refer to the built-in Powerlines plugins directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{builtinPath\}/content"
   */
  generatedPath?: string;
}

export type ContentCollectionsPluginUserConfig = UserConfig & {
  contentCollections?: ContentCollectionsPluginOptions;
};

export type ContentCollectionsPluginResolvedConfig = ResolvedConfig & {
  contentCollections: Required<
    Omit<ContentCollectionsPluginOptions, "generatedPath">
  > &
    Pick<ContentCollectionsPluginOptions, "generatedPath">;
};

export type ContentCollectionsPluginContext<
  TResolvedConfig extends
    ContentCollectionsPluginResolvedConfig = ContentCollectionsPluginResolvedConfig
> = PluginContext<TResolvedConfig> & {
  contentCollections: ContentCollectionsContext;
};
