/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { UserConfig as HeyAPIUserConfig } from "@hey-api/openapi-ts";
import { OpenApi } from "@hey-api/openapi-ts";
import { UserConfig } from "powerlines/types/config";
import { PluginContext } from "powerlines/types/context";
import { ResolvedConfig } from "powerlines/types/resolved";

export type HeyAPIPluginOutputOptions = HeyAPIUserConfig["output"] & {
  /**
   * The path to the output file generated by the plugin.
   *
   *    @remarks
   * If using the default value, the file can be imported from "powerlines:api". This field allows the use of the "\{builtinPath\}" token to refer to the built-in Powerlines plugins directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{builtinPath\}/api"
   */
  path?: string;
};

export type HeyAPIPluginOptions = Omit<HeyAPIUserConfig, "input" | "output"> & {
  /**
   * The path to the Hey API schema file.
   *
   * @remarks
   * This can be a string path, URL, HeyAPI3 object, Buffer, or Readable stream.
   *
   * @defaultValue "\{projectRoot\}/schema.yaml"
   */
  schema?: HeyAPIUserConfig["input"];

  /**
   * The output details of the Hey API generation
   */
  output?: HeyAPIPluginOutputOptions;
};

export type HeyAPIPluginUserConfig = UserConfig & {
  heyApi?: HeyAPIPluginOptions;
};

export type HeyAPIPluginResolvedConfig = ResolvedConfig & {
  heyApi: Omit<HeyAPIPluginOptions, "schema"> & {
    schema: HeyAPIPluginOptions["schema"] | OpenApi.V3_0_X;
  };
};

export type HeyAPIPluginContext<
  TResolvedConfig extends HeyAPIPluginResolvedConfig =
    HeyAPIPluginResolvedConfig
> = PluginContext<TResolvedConfig>;
