packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  '@alloy-js/babel-plugin': ^0.2.1
  '@alloy-js/babel-plugin-jsx-dom-expressions': ^0.39.1
  '@alloy-js/babel-preset': ^0.2.1
  '@alloy-js/core': ^0.22.0
  '@alloy-js/json': ^0.22.0
  '@alloy-js/markdown': ^0.22.0
  '@alloy-js/rollup-plugin': ^0.1.0
  '@alloy-js/typescript': ^0.22.0
  '@asyncapi/generator': ^2.11.0
  '@asyncapi/parser': ^3.4.0
  '@babel/core': ^7.28.6
  '@babel/generator': ^7.28.6
  '@babel/helper-module-imports': ^7.28.6
  '@babel/helper-module-transforms': ^7.28.6
  '@babel/helper-plugin-utils': ^7.28.6
  '@babel/helper-simple-access': ^7.27.1
  '@babel/parser': ^7.28.6
  '@babel/plugin-proposal-decorators': ^7.28.6
  '@babel/plugin-syntax-class-properties': ^7.12.13
  '@babel/plugin-syntax-import-assertions': ^7.28.6
  '@babel/plugin-syntax-jsx': ^7.28.6
  '@babel/plugin-syntax-typescript': ^7.28.6
  '@babel/plugin-transform-export-namespace-from': ^7.27.1
  '@babel/plugin-transform-react-jsx': ^7.28.6
  '@babel/plugin-transform-typescript': ^7.28.6
  '@babel/preset-typescript': ^7.28.5
  '@babel/template': ^7.28.6
  '@babel/traverse': ^7.28.6
  '@babel/types': ^7.28.6
  '@biomejs/biome': ^2.3.11
  '@cacheable/memory': ^2.0.7
  '@content-collections/core': ^0.12.0
  '@deepkit/core': 1.0.5
  '@deepkit/type': 1.0.5
  '@deepkit/type-compiler': 1.0.5
  '@deepkit/type-spec': 1.0.1
  '@donedeal0/superdiff': ^3.2.0
  '@graphql-codegen/cli': ^6.1.1
  '@graphql-codegen/plugin-helpers': ^6.1.0
  '@hey-api/openapi-ts': ^0.88.2
  '@jest/reporters': ^30.2.0
  '@jest/test-result': ^30.2.0
  '@jest/types': ^30.2.0
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.55.2
  '@microsoft/tsdoc': ^0.15.1
  '@microsoft/tsdoc-config': ^0.17.1
  '@noble/ciphers': ^2.1.1
  '@nx/devkit': ^22.3.3
  '@nx/eslint-plugin': ^22.3.3
  '@nx/jest': ^22.3.3
  '@nx/js': ^22.3.3
  '@nx/plugin': ^22.3.3
  '@nx/workspace': ^22.3.3
  '@prisma/get-platform': ^6.19.2
  '@prisma/prisma-schema-wasm': 6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773
  '@pulumi/pulumi': ^3.215.0
  '@rollup/plugin-alias': ^6.0.0
  '@rollup/plugin-babel': ^6.1.0
  '@rollup/plugin-commonjs': ^28.0.9
  '@rollup/plugin-inject': ^5.0.5
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rollup/plugin-replace': ^6.0.3
  '@rspack/core': ^1.7.2
  '@standard-schema/spec': ^1.1.0
  '@storm-software/build-tools': ^0.158.78
  '@storm-software/config': ^1.135.0
  '@storm-software/config-tools': ^1.188.78
  '@storm-software/cspell': ^0.45.74
  '@storm-software/esbuild': ^0.53.78
  '@storm-software/eslint': ^0.169.79
  '@storm-software/git-tools': ^2.124.61
  '@storm-software/linting-tools': ^1.132.78
  '@storm-software/markdownlint': ^0.30.74
  '@storm-software/pnpm-tools': ^0.6.80
  '@storm-software/prettier': ^0.57.74
  '@storm-software/testing-tools': ^1.119.74
  '@storm-software/tsconfig': ^0.47.74
  '@storm-software/tsup': ^0.2.76
  '@storm-software/unbuild': ^0.57.78
  '@storm-software/untyped': ^0.24.59
  '@storm-software/workspace-tools': ^1.294.24
  '@stryke/capnp': ^0.12.54
  '@stryke/cli': ^0.13.1
  '@stryke/convert': ^0.6.31
  '@stryke/env': ^0.20.46
  '@stryke/fs': ^0.33.29
  '@stryke/hash': ^0.12.35
  '@stryke/helpers': ^0.9.33
  '@stryke/http': ^0.12.22
  '@stryke/json': ^0.9.34
  '@stryke/path': ^0.24.2
  '@stryke/string-format': ^0.13.0
  '@stryke/type-checks': ^0.5.16
  '@stryke/types': ^0.10.30
  '@stryke/unique-id': ^0.3.40
  '@swc-node/register': ^1.11.1
  '@swc/core': ^1.15.8
  '@swc/helpers': ^0.5.18
  '@tamagui/static-worker': ^1.144.1
  '@tamagui/types': ^1.144.1
  '@taplo/cli': ^0.7.0
  '@types/babel__core': ^7.20.5
  '@types/babel__helper-module-imports': ^7.18.3
  '@types/babel__helper-plugin-utils': ^7.10.3
  '@types/babel__template': ^7.4.4
  '@types/babel__traverse': ^7.28.0
  '@types/bun': ^1.3.6
  '@types/diff-match-patch': ^1.0.36
  '@types/jest': ^30.0.0
  '@types/node': ^24.10.8
  '@types/pluralize': ^0.0.33
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@types/semver': ^7.7.1
  '@typescript-eslint/utils': ^8.53.0
  '@vitejs/plugin-react': ^5.1.2
  '@vue/reactivity': 3.5.26
  '@vue/shared': 3.5.26
  automd: ^0.4.2
  babel-dead-code-elimination: ^1.0.12
  babel-plugin-parameter-decorator: ^1.0.16
  babel-plugin-react-compiler: ^1.0.0
  bun-types-no-globals: ^1.3.6
  bundle-require: ^5.1.0
  c12: ^3.3.3
  chalk: 5.6.2
  compatx: ^0.2.0
  copyfiles: ^2.4.1
  defu: ^6.1.4
  diff-match-patch: ^1.0.5
  dts-bundle-generator: ^9.5.1
  esbuild: ^0.25.12
  esbuild-plugin-babel: ^0.2.3
  eslint: ^9.39.2
  eslint-flat-config-utils: ^2.1.4
  flat-cache: ^6.1.19
  fp-ts: ^2.16.11
  github-slugger: ^2.0.0
  handlebars: ^4.7.8
  i18next-cli: ^1.36.1
  i18next-resources-for-ts: ^2.0.0
  jest: ^30.2.0
  jest-config: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jest-resolve: ^30.2.0
  jest-util: ^30.2.0
  jest-worker: ^30.2.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  magic-string: ^0.30.21
  markdown-toc: ^1.2.0
  marked: ^17.0.1
  minimatch: ^10.1.1
  nanotar: ^0.2.0
  nitro: 3.0.1-alpha.1
  nx: ^22.3.3
  openapi-typescript: ^7.10.1
  oxc-parser: ^0.99.0
  oxc-transform: ^0.99.0
  oxlint: ^1.39.0
  oxlint-tsgolint: ^0.2.1
  pluralize: ^8.0.0
  prettier: ^3.7.4
  prisma-util: ^2.1.1
  react: ^19.2.3
  react-dom: ^19.2.3
  rimraf: ^6.1.2
  rolldown: 1.0.0-beta.53
  rollup: ^4.55.1
  rollup-plugin-typescript2: ^0.36.0
  satori: ^0.18.3
  sharp: ^0.34.5
  sherif: ^1.9.0
  style-dictionary: ^5.1.4
  stylelint: ^16.26.1
  svgo: ^4.0.0
  ts-jest: 29.4.0
  ts-morph: ^27.0.2
  ts-pattern: ^5.9.0
  tsdown: 0.17.0-beta.5
  tslib: ^2.8.1
  tsup: 8.4.0
  typedoc: 0.25.12
  typedoc-plugin-markdown: 4.0.0-next.20
  undici: ^7.18.2
  undici-types: ^7.18.2
  unenv: npm:unenv-nightly@2.0.0-rc.24
  unimport: ^5.6.0
  unplugin: 3.0.0-beta.3
  untyped: ^1.5.2
  verdaccio: 6.1.2
  vite: 8.0.0-beta.2
  webpack: ^5.104.1
  zx: ^8.8.5

configDependencies:
  pnpm-plugin-storm-software: 0.1.4+sha512-Hegfb70ijqCc65CZwy8aLYhxrYQv3Wo+MZXqSfNAfcge7iSGYm2J3ydU5zkmf89JSvMOJy8J6lo/TMynBGvgtA==

fetchTimeout: 240000

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'
  - powerlines
  - '@earthquake/*'
  - earthquake

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@deepkit/type-compiler'
  - '@hyperjump/json-pointer'
  - '@hyperjump/json-schema'
  - '@hyperjump/json-schema-core'
  - '@hyperjump/pact'
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd

overrides:
  '@powerlines/deepkit': workspace:*
  '@powerlines/nx': workspace:*
  '@powerlines/plugin-alloy': workspace:*
  '@powerlines/plugin-asyncapi': workspace:*
  '@powerlines/plugin-automd': workspace:*
  '@powerlines/plugin-babel': workspace:*
  '@powerlines/plugin-biome': workspace:*
  '@powerlines/plugin-capnp': workspace:*
  '@powerlines/plugin-content-collections': workspace:*
  '@powerlines/plugin-crypto': workspace:*
  '@powerlines/plugin-date': workspace:*
  '@powerlines/plugin-deepkit': workspace:*
  '@powerlines/plugin-env': workspace:*
  '@powerlines/plugin-esbuild': workspace:*
  '@powerlines/plugin-eslint': workspace:*
  '@powerlines/plugin-graphql': workspace:*
  '@powerlines/plugin-hey-api': workspace:*
  '@powerlines/plugin-i18next': workspace:*
  '@powerlines/plugin-id': workspace:*
  '@powerlines/plugin-image-compression': workspace:*
  '@powerlines/plugin-jest': workspace:*
  '@powerlines/plugin-marked': workspace:*
  '@powerlines/plugin-nitro': workspace:*
  '@powerlines/plugin-nodejs': workspace:*
  '@powerlines/plugin-openapi': workspace:*
  '@powerlines/plugin-oxc-transform': workspace:*
  '@powerlines/plugin-oxlint': workspace:*
  '@powerlines/plugin-plugin': workspace:*
  '@powerlines/plugin-prisma': workspace:*
  '@powerlines/plugin-pulumi': workspace:*
  '@powerlines/plugin-react': workspace:*
  '@powerlines/plugin-rolldown': workspace:*
  '@powerlines/plugin-rollup': workspace:*
  '@powerlines/plugin-rspack': workspace:*
  '@powerlines/plugin-satori': workspace:*
  '@powerlines/plugin-style-dictionary': workspace:*
  '@powerlines/plugin-stylelint': workspace:*
  '@powerlines/plugin-swc': workspace:*
  '@powerlines/plugin-tamagui': workspace:*
  '@powerlines/plugin-tsc': workspace:*
  '@powerlines/plugin-tsdown': workspace:*
  '@powerlines/plugin-tsup': workspace:*
  '@powerlines/plugin-typedoc': workspace:*
  '@powerlines/plugin-unbuild': workspace:*
  '@powerlines/plugin-unenv': workspace:*
  '@powerlines/plugin-unimport': workspace:*
  '@powerlines/plugin-untyped': workspace:*
  '@powerlines/plugin-vite': workspace:*
  '@powerlines/plugin-webpack': workspace:*
  '@powerlines/tools-config': workspace:*
  '@powerlines/tools-nx': workspace:*
  '@powerlines/tools-readme-templates': workspace:*
  '@powerlines/tools-scripts': workspace:*
  '@powerlines/tsconfig': workspace:*
  debug: '>=4.3.7'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.2'
  ip: '>=2.0.1'
  loader-utils: '>=3.3.1'
  lru-cache: ^8.0.5
  markdown-it: '>=14.1.0'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  postcss: '>=8.4.47'
  powerlines: workspace:*
  shell-quote: '>=1.8.1'
  simple-git: '>=3.27.0'
  zod: '>=4.0.1'

patchedDependencies:
  '@alloy-js/babel-plugin-jsx-dom-expressions': patches/@alloy-js__babel-plugin-jsx-dom-expressions.patch
  '@content-collections/core': patches/@content-collections__core.patch
  '@deepkit/core': patches/@deepkit__core.patch
  '@deepkit/type': patches/@deepkit__type.patch
  '@deepkit/type-compiler': patches/@deepkit__type-compiler.patch
  '@deepkit/type-spec': patches/@deepkit__type-spec.patch
  '@vue/reactivity': patches/@vue__reactivity.patch
  automd: patches/automd.patch
  prisma-util: patches/prisma-util.patch

shamefullyHoist: true

trustPolicy: off

useNodeVersion: 24.11.1
