onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - lefthook
  - nx
packages:
  - "tools/*"
  - "packages/*"
  - "docs/*"

catalog:
  "@ls-lint/ls-lint": ^2.2.3
  "@microsoft/api-extractor": "^7.49.2"
  "@taplo/cli": ^0.7.0
  "@types/jest": "^29.5.14"
  "@types/node": ^22.10.2
  "@nx/devkit": 20.7.0
  "@nx/eslint-plugin": 20.7.0
  "@nx/jest": 20.7.0
  "@nx/js": 20.7.0
  "@nx/plugin": 20.7.0
  "@nx/workspace": 20.7.0
  "@storm-software/config": "latest"
  "@storm-software/config-tools": "latest"
  "@storm-software/cspell": "latest"
  "@storm-software/git-tools": "latest"
  "@storm-software/linting-tools": "latest"
  "@storm-software/esbuild": "latest"
  "@storm-software/eslint": "latest"
  "@storm-software/prettier": "latest"
  "@storm-software/unbuild": "latest"
  "@storm-software/untyped": "latest"
  "@storm-software/testing-tools": "latest"
  "@storm-software/tsconfig": "latest"
  "@storm-software/workspace-tools": "latest"
  "@storm-software/markdownlint": "latest"
  "@swc-node/register": "^1.10.9"
  "@swc/core": "^1.10.14"
  "@swc/wasm": "^1.10.14"
  "@swc/helpers": "^0.5.15"
  "lefthook": ^1.7.18
  "eslint": "^9.20.0"
  "prettier": ^3.5.2
  "nx": 20.7.0
  "jest": 29.7.0
  "jest-environment-jsdom": "^29.7.0"
  "jest-environment-node": "^29.7.0"
  "sherif": ^1.0.0
  "ts-jest": ^29.2.5
  "ts-node": ^10.9.2
  "tsup": "^8.3.5"
  "tslib": "^2.8.1"
  "copyfiles": "^2.4.1"
  "rimraf": "^6.0.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-native": "^0.77.0"
  "typescript": ~5.7.3
  "esbuild": "^0.24.2"
  "unbuild": "^3.3.1"
  "defu": "^6.1.4"
  "jiti": "^2.4.2"
  "verdaccio": 6.0.5
  "zx": ^8.3.2
overrides:
  "@monorepo-template/tools-scripts": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  next: ">=13.4.20-canary.13"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
