packages:
  - tools/*
  - packages/*
  - docs/*
catalog:
  "@ls-lint/ls-lint": ^2.2.3
  "@microsoft/api-extractor": ^7.49.2
  "@taplo/cli": ^0.7.0
  "@types/jest": ^29.5.14
  "@types/node": ^22.10.2
  "@nx/devkit": 21.2.2
  "@nx/eslint-plugin": 21.2.2
  "@nx/jest": 21.2.2
  "@nx/js": 21.2.2
  "@nx/plugin": 21.2.2
  "@nx/workspace": 21.2.2
  "@storm-software/build-tools": 0.151.19
  "@storm-software/config": latest
  "@storm-software/config-tools": latest
  "@storm-software/cspell": latest
  "@storm-software/git-tools": latest
  "@storm-software/linting-tools": latest
  "@storm-software/eslint": latest
  "@storm-software/prettier": latest
  "@storm-software/markdownlint": latest
  "@storm-software/esbuild": latest
  "@storm-software/unbuild": latest
  "@storm-software/untyped": latest
  "@storm-software/testing-tools": latest
  "@storm-software/tsconfig": latest
  "@storm-software/tsdoc": latest
  "@storm-software/workspace-tools": latest
  "@swc-node/register": ^1.10.10
  "@swc/core": ^1.11.22
  "@swc/wasm": ^1.11.24
  "@swc/helpers": ^0.5.17
  lefthook: ^1.11.12
  log4brains: ^1.1.0
  eslint: ^9.27.0
  prettier: ^3.6.2
  nx: 21.2.2
  jest: ^30.0.0-beta.3
  jest-environment-jsdom: ^30.0.0-beta.3
  jest-environment-node: ^30.0.0-beta.3
  sherif: ^1.0.0
  ts-jest: ^29.2.5
  ts-node: ^10.9.2
  tsup: ^8.3.5
  tslib: ^2.8.1
  copyfiles: ^2.4.1
  rimraf: ^6.0.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-native: ^0.77.0
  typescript: 5.8.3
  esbuild: ^0.25.0
  unbuild: ^3.3.1
  defu: ^6.1.4
  jiti: ^2.4.2
  verdaccio: 6.0.5
  zx: ^8.3.2
linkWorkspacePackages: true
onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - lefthook
  - nx
  - sharp
overrides:
  "@monorepo-template/tools-scripts": workspace:*
  "@monorepo-template/tools-config": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  next: ">=13.4.20-canary.13"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
  zod: ">=4.0.5"
