packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  "@alloy-js/babel-plugin": ^0.2.1
  "@alloy-js/babel-plugin-jsx-dom-expressions": ^0.39.1
  "@alloy-js/babel-preset": ^0.2.1
  "@alloy-js/core": ^0.20.0
  "@alloy-js/json": ^0.20.0
  "@alloy-js/markdown": ^0.20.0
  "@alloy-js/rollup-plugin": ^0.1.0
  "@alloy-js/typescript": ^0.20.0
  "@babel/core": ^7.28.4
  "@babel/generator": ^7.28.3
  "@babel/helper-module-imports": ^7.27.1
  "@babel/helper-module-transforms": ^7.28.3
  "@babel/helper-plugin-utils": ^7.27.1
  "@babel/helper-simple-access": ^7.27.1
  "@babel/parser": ^7.28.4
  "@babel/plugin-proposal-decorators": ^7.28.0
  "@babel/plugin-syntax-class-properties": ^7.12.13
  "@babel/plugin-syntax-import-assertions": ^7.27.1
  "@babel/plugin-syntax-jsx": ^7.27.1
  "@babel/plugin-syntax-typescript": ^7.27.1
  "@babel/plugin-transform-export-namespace-from": ^7.27.1
  "@babel/plugin-transform-react-jsx": ^7.27.1
  "@babel/plugin-transform-typescript": ^7.28.0
  "@babel/preset-typescript": ^7.27.1
  "@babel/template": ^7.27.2
  "@babel/traverse": ^7.28.4
  "@babel/types": ^7.28.4
  "@deepkit/core": 1.0.5
  "@deepkit/type": 1.0.5
  "@deepkit/type-compiler": 1.0.5
  "@deepkit/type-spec": 1.0.1
  "@donedeal0/superdiff": ^3.1.2
  "@ls-lint/ls-lint": ^2.3.1
  "@microsoft/api-extractor": ^7.53.1
  "@microsoft/tsdoc": ^0.15.1
  "@microsoft/tsdoc-config": ^0.17.1
  "@nx/devkit": 21.5.3
  "@nx/eslint-plugin": 21.5.3
  "@nx/jest": 21.5.3
  "@nx/js": 21.5.3
  "@nx/plugin": 21.5.3
  "@nx/workspace": 21.5.3
  "@rollup/plugin-alias": ^5.1.1
  "@rollup/plugin-babel": ^6.1.0
  "@rollup/plugin-commonjs": ^28.0.8
  "@rollup/plugin-node-resolve": ^16.0.3
  "@storm-software/build-tools": ^0.158.6
  "@storm-software/config": ^1.134.6
  "@storm-software/config-tools": ^1.188.6
  "@storm-software/cspell": ^0.45.6
  "@storm-software/esbuild": ^0.53.6
  "@storm-software/eslint": ^0.169.6
  "@storm-software/git-tools": ^2.123.6
  "@storm-software/linting-tools": ^1.132.6
  "@storm-software/markdownlint": ^0.30.6
  "@storm-software/prettier": ^0.57.6
  "@storm-software/testing-tools": ^1.119.6
  "@storm-software/tsconfig": ^0.47.6
  "@storm-software/tsdoc": ^0.13.6
  "@storm-software/tsup": ^0.2.4
  "@storm-software/unbuild": ^0.57.6
  "@storm-software/untyped": ^0.23.6
  "@storm-software/workspace-tools": ^1.292.6
  "@stryke/capnp": ^0.12.2
  "@stryke/convert": ^0.6.0
  "@stryke/env": ^0.20.2
  "@stryke/fs": ^0.32.2
  "@stryke/hash": ^0.12.0
  "@stryke/helpers": ^0.9.2
  "@stryke/json": ^0.9.3
  "@stryke/path": ^0.16.0
  "@stryke/string-format": ^0.12.0
  "@stryke/type-checks": ^0.3.10
  "@stryke/types": ^0.10.0
  "@stryke/unique-id": ^0.3.5
  "@taplo/cli": ^0.7.0
  "@types/babel__core": ^7.20.5
  "@types/babel__helper-module-imports": ^7.18.3
  "@types/babel__helper-plugin-utils": ^7.10.3
  "@types/babel__template": ^7.4.4
  "@types/babel__traverse": ^7.28.0
  "@types/diff-match-patch": ^1.0.36
  "@types/jest": 30.0.0
  "@types/node": ^22.18.12
  "@types/semver": ^7.7.1
  "@vue/reactivity": ^3.5.22
  babel-dead-code-elimination: ^1.0.10
  babel-plugin-parameter-decorator: ^1.0.16
  bundle-require: ^5.1.0
  c12: ^3.3.1
  chalk: ^5.6.2
  copyfiles: ^2.4.1
  defu: ^6.1.4
  diff-match-patch: ^1.0.5
  esbuild: ^0.25.11
  esbuild-plugin-babel: ^0.2.3
  eslint: ^9.38.0
  eslint-flat-config-utils: 2.1.0
  github-slugger: ^2.0.0
  handlebars: ^4.7.8
  jest: 30.0.5
  jest-environment-jsdom: 30.0.5
  jest-environment-node: 30.0.5
  jest-worker: 30.0.5
  jiti: ^2.6.1
  jsonc-eslint-parser: 2.4.0
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  magic-string: ^0.30.19
  memfs: ^4.49.0
  minimatch: ^10.0.3
  nanotar: ^0.2.0
  nx: 21.5.3
  oxc-transform: ^0.95.0
  prettier: ^3.6.2
  rimraf: ^6.0.1
  rolldown: 1.0.0-beta.44
  rollup: ^4.52.5
  rollup-plugin-typescript2: ^0.36.0
  sherif: ^1.6.1
  ts-jest: 29.4.0
  ts-node: ^10.9.2
  tslib: ^2.8.1
  tsup: 8.4.0
  typedoc: 0.25.12
  typedoc-plugin-markdown: 4.0.0-next.20
  unimport: ^4.2.0
  unionfs: ^4.6.0
  unplugin: ^2.3.10
  untyped: 1.5.2
  verdaccio: 6.1.2
  vite: ^7.1.11
  zx: ^8.8.5

catalogMode: prefer

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

minimumReleaseAge: 740

minimumReleaseAgeExclude:
  - "@storm-software/*"
  - "@stryke/*"
  - "@powerlines/*"
  - "@vitest/eslint-plugin"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@deepkit/type-compiler"
  - "@swc/core"
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd

overrides:
  "@powerlines/alloy": workspace:*
  "@powerlines/nx": workspace:*
  "@powerlines/plugin-babel": workspace:*
  "@powerlines/plugin-crypto": workspace:*
  "@powerlines/plugin-date": workspace:*
  "@powerlines/plugin-deepkit": workspace:*
  "@powerlines/plugin-env": workspace:*
  "@powerlines/plugin-esbuild": workspace:*
  "@powerlines/plugin-id": workspace:*
  "@powerlines/plugin-oxc-transform": workspace:*
  "@powerlines/plugin-plugin": workspace:*
  "@powerlines/plugin-rolldown": workspace:*
  "@powerlines/plugin-rollup": workspace:*
  "@powerlines/plugin-tsup": workspace:*
  "@powerlines/plugin-typedoc": workspace:*
  "@powerlines/plugin-vite": workspace:*
  "@powerlines/tools-config": workspace:*
  "@powerlines/tools-readme-templates": workspace:*
  "@powerlines/tools-scripts": workspace:*
  "@powerlines/tsconfig": workspace:*
  "@powerlines/tsdoc": workspace:*
  debug: ">=4.3.7"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.2"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  lru-cache: ^8.0.5
  markdown-it: ">=14.1.0"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  postcss: ">=8.4.47"
  powerlines: workspace:*
  shell-quote: ">=1.8.1"
  simple-git: ">=3.27.0"
  zod: ">=4.0.1"

patchedDependencies:
  "@alloy-js/babel-plugin-jsx-dom-expressions": patches/@alloy-js__babel-plugin-jsx-dom-expressions.patch
  "@alloy-js/core": patches/@alloy-js__core.patch
  "@deepkit/core": patches/@deepkit__core.patch
  "@deepkit/type": patches/@deepkit__type.patch
  "@deepkit/type-compiler": patches/@deepkit__type-compiler.patch
  "@deepkit/type-spec": patches/@deepkit__type-spec.patch

preferWorkspacePackages: true
