packages:
  - tools/*
  - packages/*
  - docs/*

catalog:
  '@alloy-js/babel-plugin': ^0.2.1
  '@alloy-js/babel-plugin-jsx-dom-expressions': ^0.39.1
  '@alloy-js/babel-preset': ^0.2.1
  '@alloy-js/core': ^0.20.0
  '@alloy-js/json': ^0.20.0
  '@alloy-js/markdown': ^0.20.0
  '@alloy-js/rollup-plugin': ^0.1.0
  '@alloy-js/typescript': ^0.20.0
  '@asyncapi/generator': ^2.8.3
  '@asyncapi/parser': ^3.4.0
  '@babel/core': ^7.28.5
  '@babel/generator': ^7.28.5
  '@babel/helper-module-imports': ^7.27.1
  '@babel/helper-module-transforms': ^7.28.3
  '@babel/helper-plugin-utils': ^7.27.1
  '@babel/helper-simple-access': ^7.27.1
  '@babel/parser': ^7.28.5
  '@babel/plugin-proposal-decorators': ^7.28.0
  '@babel/plugin-syntax-class-properties': ^7.12.13
  '@babel/plugin-syntax-import-assertions': ^7.27.1
  '@babel/plugin-syntax-jsx': ^7.27.1
  '@babel/plugin-syntax-typescript': ^7.27.1
  '@babel/plugin-transform-export-namespace-from': ^7.27.1
  '@babel/plugin-transform-react-jsx': ^7.27.1
  '@babel/plugin-transform-typescript': ^7.28.5
  '@babel/preset-typescript': ^7.28.5
  '@babel/template': ^7.27.2
  '@babel/traverse': ^7.28.5
  '@babel/types': ^7.28.5
  '@biomejs/biome': ^2.3.3
  '@deepkit/core': 1.0.5
  '@deepkit/type': 1.0.5
  '@deepkit/type-compiler': 1.0.5
  '@deepkit/type-spec': 1.0.1
  '@donedeal0/superdiff': ^3.1.2
  '@graphql-codegen/cli': ^6.0.1
  '@graphql-codegen/plugin-helpers': ^6.0.0
  '@jest/reporters': ^30.2.0
  '@jest/test-result': ^30.2.0
  '@jest/types': ^30.2.0
  '@ls-lint/ls-lint': ^2.3.1
  '@microsoft/api-extractor': ^7.54.0
  '@microsoft/tsdoc': ^0.15.1
  '@microsoft/tsdoc-config': ^0.17.1
  '@nx/devkit': ^22.0.2
  '@nx/eslint-plugin': ^22.0.2
  '@nx/jest': ^22.0.2
  '@nx/js': ^22.0.2
  '@nx/plugin': ^22.0.2
  '@nx/workspace': ^22.0.2
  '@prisma/get-platform': ^6.18.0
  '@prisma/prisma-schema-wasm': 6.19.0-26.2ba551f319ab1df4bc874a89965d8b3641056773
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-babel': ^6.1.0
  '@rollup/plugin-commonjs': ^28.0.9
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rspack/core': ^1.6.0
  '@storm-software/build-tools': ^0.158.19
  '@storm-software/config': ^1.134.19
  '@storm-software/config-tools': ^1.188.19
  '@storm-software/cspell': ^0.45.19
  '@storm-software/esbuild': ^0.53.19
  '@storm-software/eslint': ^0.169.19
  '@storm-software/git-tools': ^2.124.0
  '@storm-software/linting-tools': ^1.132.19
  '@storm-software/markdownlint': ^0.30.19
  '@storm-software/prettier': ^0.57.19
  '@storm-software/testing-tools': ^1.119.19
  '@storm-software/tsconfig': ^0.47.19
  '@storm-software/tsup': ^0.2.17
  '@storm-software/unbuild': ^0.57.19
  '@storm-software/untyped': ^0.23.19
  '@storm-software/workspace-tools': ^1.292.19
  '@stryke/capnp': ^0.12.18
  '@stryke/cli': ^0.12.4
  '@stryke/convert': ^0.6.0
  '@stryke/env': ^0.20.11
  '@stryke/fs': ^0.32.10
  '@stryke/hash': ^0.12.0
  '@stryke/helpers': ^0.9.2
  '@stryke/http': ^0.11.1
  '@stryke/json': ^0.9.3
  '@stryke/path': ^0.18.5
  '@stryke/string-format': ^0.12.0
  '@stryke/type-checks': ^0.3.10
  '@stryke/types': ^0.10.0
  '@stryke/unique-id': ^0.3.5
  '@swc/core': ^1.15.0
  '@taplo/cli': ^0.7.0
  '@types/babel__core': ^7.20.5
  '@types/babel__helper-module-imports': ^7.18.3
  '@types/babel__helper-plugin-utils': ^7.10.3
  '@types/babel__template': ^7.4.4
  '@types/babel__traverse': ^7.28.0
  '@types/diff-match-patch': ^1.0.36
  '@types/jest': ^30.0.0
  '@types/node': ^22.19.0
  '@types/semver': ^7.7.1
  '@typescript-eslint/utils': ^8.46.3
  '@vitejs/plugin-react': ^5.1.0
  '@vue/reactivity': ^3.5.22
  automd: ^0.4.2
  babel-dead-code-elimination: ^1.0.10
  babel-plugin-parameter-decorator: ^1.0.16
  babel-plugin-react-compiler: ^1.0.0
  bundle-require: ^5.1.0
  c12: ^3.3.1
  chalk: 5.6.2
  copyfiles: ^2.4.1
  defu: ^6.1.4
  diff-match-patch: ^1.0.5
  esbuild: ^0.25.12
  esbuild-plugin-babel: ^0.2.3
  eslint: ^9.39.1
  eslint-flat-config-utils: ^2.1.4
  fp-ts: ^2.16.11
  github-slugger: ^2.0.0
  handlebars: ^4.7.8
  jest: ^30.2.0
  jest-config: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-environment-node: ^30.2.0
  jest-resolve: ^30.2.0
  jest-util: ^30.2.0
  jest-worker: ^30.2.0
  jiti: ^2.6.1
  jsonc-eslint-parser: ^2.4.1
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  magic-string: ^0.30.21
  markdown-toc: ^1.2.0
  memfs: ^4.50.0
  minimatch: ^10.1.1
  nanotar: ^0.2.0
  nx: ^22.0.2
  openapi-typescript: ^7.10.1
  oxc-parser: ^0.95.0
  oxc-transform: ^0.95.0
  oxlint: ^1.25.0
  oxlint-tsgolint: ^0.2.1
  prettier: ^3.6.2
  rimraf: ^6.1.0
  rolldown: 1.0.0-beta.45
  rolldown-vite: ^7.1.20
  rollup: ^4.52.5
  rollup-plugin-typescript2: ^0.36.0
  sherif: ^1.8.0
  style-dictionary: ^5.1.1
  stylelint: ^16.25.0
  ts-jest: 29.4.0
  ts-morph: ^27.0.2
  ts-node: ^10.9.2
  ts-pattern: ^5.9.0
  tslib: ^2.8.1
  tsup: 8.4.0
  typedoc: 0.25.12
  typedoc-plugin-markdown: 4.0.0-next.20
  unimport: ^5.5.0
  unionfs: ^4.6.0
  unplugin: ^2.3.10
  untyped: 1.5.2
  verdaccio: 6.1.2
  vite: ^7.1.12
  webpack: ^5.102.1
  zx: ^8.8.5

catalogMode: prefer

cleanupUnusedCatalogs: true

linkWorkspacePackages: true

minimumReleaseAge: 800

minimumReleaseAgeExclude:
  - '@storm-software/*'
  - '@stryke/*'
  - '@powerlines/*'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@hyperjump/json-pointer'
  - '@hyperjump/json-schema'
  - '@hyperjump/json-schema-core'
  - '@hyperjump/pact'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - nx
  - oxc-resolver
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd

overrides:
  '@powerlines/alloy': workspace:*
  '@powerlines/deepkit': workspace:*
  '@powerlines/nx': workspace:*
  '@powerlines/plugin-asyncapi': workspace:*
  '@powerlines/plugin-automd': workspace:*
  '@powerlines/plugin-babel': workspace:*
  '@powerlines/plugin-biome': workspace:*
  '@powerlines/plugin-capnp': workspace:*
  '@powerlines/plugin-crypto': workspace:*
  '@powerlines/plugin-date': workspace:*
  '@powerlines/plugin-deepkit': workspace:*
  '@powerlines/plugin-env': workspace:*
  '@powerlines/plugin-esbuild': workspace:*
  '@powerlines/plugin-eslint': workspace:*
  '@powerlines/plugin-graphql': workspace:*
  '@powerlines/plugin-id': workspace:*
  '@powerlines/plugin-jest': workspace:*
  '@powerlines/plugin-openapi': workspace:*
  '@powerlines/plugin-oxc-transform': workspace:*
  '@powerlines/plugin-oxlint': workspace:*
  '@powerlines/plugin-plugin': workspace:*
  '@powerlines/plugin-prisma': workspace:*
  '@powerlines/plugin-react': workspace:*
  '@powerlines/plugin-rolldown': workspace:*
  '@powerlines/plugin-rollup': workspace:*
  '@powerlines/plugin-rspack': workspace:*
  '@powerlines/plugin-style-dictionary': workspace:*
  '@powerlines/plugin-stylelint': workspace:*
  '@powerlines/plugin-swc': workspace:*
  '@powerlines/plugin-tsc': workspace:*
  '@powerlines/plugin-tsup': workspace:*
  '@powerlines/plugin-typedoc': workspace:*
  '@powerlines/plugin-unbuild': workspace:*
  '@powerlines/plugin-unimport': workspace:*
  '@powerlines/plugin-untyped': workspace:*
  '@powerlines/plugin-vite': workspace:*
  '@powerlines/plugin-webpack': workspace:*
  '@powerlines/tools-config': workspace:*
  '@powerlines/tools-nx': workspace:*
  '@powerlines/tools-readme-templates': workspace:*
  '@powerlines/tools-scripts': workspace:*
  '@powerlines/tsconfig': workspace:*
  debug: '>=4.3.7'
  follow-redirects: '>=1.15.9'
  got: '>=14.4.2'
  ip: '>=2.0.1'
  loader-utils: '>=3.3.1'
  lru-cache: ^8.0.5
  markdown-it: '>=14.1.0'
  node-fetch: '>=3.3.2'
  nth-check: '>=2.1.1'
  parse-path: '>=7.0.0'
  parse-url: '>=9.2.0'
  postcss: '>=8.4.47'
  powerlines: workspace:*
  shell-quote: '>=1.8.1'
  simple-git: '>=3.27.0'
  zod: '>=4.0.1'

patchedDependencies:
  '@alloy-js/babel-plugin-jsx-dom-expressions': patches/@alloy-js__babel-plugin-jsx-dom-expressions.patch
  '@alloy-js/core': patches/@alloy-js__core.patch
  '@deepkit/core': patches/@deepkit__core.patch
  '@deepkit/type': patches/@deepkit__type.patch
  '@deepkit/type-compiler': patches/@deepkit__type-compiler.patch
  '@deepkit/type-spec': patches/@deepkit__type-spec.patch
  automd: patches/automd.patch
  prisma-util: patches/prisma-util.patch

preferWorkspacePackages: true
