/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { PluginContext, ResolvedConfig, UserConfig } from "powerlines";
import { PrismaClient } from "../api/sdk.gen";
import { PrismaSchemaCreator } from "../helpers/schema-creator";
import { PrismaSchema } from "./prisma";

export interface PrismaPostgresPrismaPluginOptions {
  /**
   * The Prisma project name
   *
   * @defaultValue "\{name\}"
   */
  projectId?: string;

  /**
   * The region to deploy the database to
   *
   * @defaultValue "us-east-1"
   */
  region?:
    | "us-east-1"
    | "us-east-2"
    | "us-west-1"
    | "us-west-2"
    | "af-south-1"
    | "ap-east-1"
    | "ap-south-1"
    | "ap-south-2"
    | "ap-southeast-1"
    | "ap-southeast-2"
    | "ap-southeast-3"
    | "ap-southeast-4"
    | "ap-northeast-1"
    | "ap-northeast-2"
    | "ap-northeast-3"
    | "ca-central-1"
    | "ca-west-1"
    | "eu-central-1"
    | "eu-central-2"
    | "eu-west-1"
    | "eu-west-2"
    | "eu-west-3"
    | "eu-north-1"
    | "eu-south-1"
    | "eu-south-2"
    | "il-central-1"
    | "me-south-1"
    | "me-central-1"
    | "sa-east-1";

  /**
   * The database name
   *
   * @defaultValue "\{region\}.\{mode\}.\{name\}"
   */
  databaseName?: string;
}

export interface PrismaPluginOptions {
  /**
   * The path to the Prisma schema file (PSL).
   *
   * @defaultValue "\{projectRoot\}/prisma/schema.prisma"
   */
  schema?: string;

  /**
   * The path to a custom Prisma configuration file.
   *
   * @remarks
   * This field allows the use of the "\{projectRoot\}" token to refer to the project's root directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{projectRoot\}/prisma.config.ts"
   */
  configFile?: string;

  /**
   * The path to the output file generated by the plugin.
   *
   * @remarks
   * If using the default value, the file can be imported from "powerlines:prisma/module-name". This field allows the use of the "\{builtinPath\}" token to refer to the built-in Powerlines plugins directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{builtinPath\}/prisma"
   */
  outputPath?: string;

  /**
   * Additional parameters to pass to the Prisma CLI
   */
  params?: string;

  /**
   * The path to the Prisma binary
   */
  prismaPath?: string;

  /**
   * The service token to use for the Prisma API
   */
  serviceToken?: string;

  /**
   * Configuration parameters to manage a Prisma Postgres database
   */
  prismaPostgres?: PrismaPostgresPrismaPluginOptions | true;
}

export type PrismaPluginUserConfig = UserConfig & {
  prisma?: Omit<PrismaPluginOptions, "schema" | "outputPath" | "configFile"> &
    Required<Pick<PrismaPluginOptions, "schema" | "outputPath" | "configFile">>;
};

export type PrismaPluginResolvedConfig = ResolvedConfig & {
  prisma: Omit<
    PrismaPluginOptions,
    "schema" | "outputPath" | "configFile" | "prismaPostgres"
  > &
    Required<
      Pick<PrismaPluginOptions, "schema" | "outputPath" | "configFile">
    > & {
      prismaPostgres?: Required<PrismaPostgresPrismaPluginOptions>;
    };
};

export type PrismaPluginContext<
  TResolvedConfig extends PrismaPluginResolvedConfig =
    PrismaPluginResolvedConfig
> = PluginContext<TResolvedConfig> & {
  prisma: {
    schema: PrismaSchema;
    builder: PrismaSchemaCreator;
    api: PrismaClient;
  };
};
