/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import {
  PulumiPluginContext,
  PulumiPluginOptions,
  PulumiPluginResolvedConfig,
  PulumiPluginUserConfig
} from "@powerlines/plugin-pulumi";
import { PrismaConfig } from "@prisma/config";
import type * as DMMF from "@prisma/dmmf";
import { SqlQueryOutput } from "@prisma/generator";
import { SchemaContext } from "@prisma/internals";
import { PluginContext, ResolvedConfig, UserConfig } from "powerlines";
import { PrismaSchemaCreator } from "../helpers/schema-creator";
import { PrismaSchema } from "./prisma";

export interface PrismaPostgresPrismaPluginOptions {
  /**
   * The Prisma project name
   *
   * @defaultValue "\{name\}"
   */
  projectId?: string;

  /**
   * The region to deploy the database to
   *
   * @defaultValue "us-east-1"
   */
  region?:
    | "us-east-1"
    | "us-east-2"
    | "us-west-1"
    | "us-west-2"
    | "af-south-1"
    | "ap-east-1"
    | "ap-south-1"
    | "ap-south-2"
    | "ap-southeast-1"
    | "ap-southeast-2"
    | "ap-southeast-3"
    | "ap-southeast-4"
    | "ap-northeast-1"
    | "ap-northeast-2"
    | "ap-northeast-3"
    | "ca-central-1"
    | "ca-west-1"
    | "eu-central-1"
    | "eu-central-2"
    | "eu-west-1"
    | "eu-west-2"
    | "eu-west-3"
    | "eu-north-1"
    | "eu-south-1"
    | "eu-south-2"
    | "il-central-1"
    | "me-south-1"
    | "me-central-1"
    | "sa-east-1";

  /**
   * The database name
   *
   * @defaultValue "\{region\}.\{mode\}.\{name\}"
   */
  databaseName?: string;
}

export interface PrismaPluginOptions extends Omit<PrismaConfig, "schema"> {
  /**
   * The path(s) to the Prisma schema file(s) (PSL), or path(s) to a folder that shall be recursively searched for *.prisma files.
   *
   * @defaultValue "\{projectRoot\}/prisma/*.prisma"
   */
  schema?: string | string[];

  /**
   * The path to a custom Prisma configuration file.
   *
   * @remarks
   * This field allows the use of the "\{projectRoot\}" token to refer to the project's root directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{projectRoot\}/prisma.config.ts"
   */
  configFile?: string;

  /**
   * The path to the output file generated by the plugin.
   *
   * @remarks
   * If using the default value, the file can be imported from "powerlines:prisma/module-name". This field allows the use of the "\{builtinsPath\}" token to refer to the built-in Powerlines plugins directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{builtinsPath\}/prisma"
   */
  outputPath?: string;

  /**
   * The runtime environment to generate the Prisma Client for.
   *
   * @defaultValue "nodejs"
   */
  runtime?: "deno" | "nodejs" | "workerd" | "vercel-edge";

  /**
   * The service token to use for the Prisma API
   */
  serviceToken?: string;

  /**
   * Configuration parameters to manage a Prisma Postgres database
   */
  prismaPostgres?: PrismaPostgresPrismaPluginOptions | true;

  /**
   * The configuration options for Pulumi.
   */
  pulumi?: PulumiPluginOptions;
}

export type PrismaPluginUserConfig = UserConfig &
  PulumiPluginUserConfig & {
    prisma?: Omit<PrismaPluginOptions, "schema" | "outputPath" | "configFile"> &
      Required<
        Pick<PrismaPluginOptions, "schema" | "outputPath" | "configFile">
      >;
  };

export type PrismaPluginResolvedConfig = ResolvedConfig &
  PulumiPluginResolvedConfig & {
    prisma: Omit<
      PrismaPluginOptions,
      "schema" | "outputPath" | "configFile" | "runtime" | "prismaPostgres"
    > &
      Required<
        Pick<PrismaPluginOptions, "outputPath" | "configFile" | "runtime">
      > & {
        /**
         * The path(s) to the Prisma schema file(s) (PSL), or path(s) to a folder that shall be recursively searched for *.prisma files.
         */
        schema: string[];

        /**
         * Configuration parameters to manage a Prisma Postgres database
         */
        prismaPostgres?: Required<PrismaPostgresPrismaPluginOptions>;
      };
  };

export type PrismaSchemaContext = Omit<
  SchemaContext,
  "warnings" | "datasources" | "generators"
> &
  Omit<PrismaSchema, "path" | "content"> & {
    schemas: PrismaSchema[];
  };

export type PrismaPluginContext<
  TResolvedConfig extends PrismaPluginResolvedConfig =
    PrismaPluginResolvedConfig
> = PluginContext<TResolvedConfig> &
  PulumiPluginContext & {
    prisma: {
      config: PrismaConfig;
      schema: PrismaSchemaContext;
      previewFeatures: string[];
      dmmf: DMMF.Document;
      builder: PrismaSchemaCreator;
      typedSql: SqlQueryOutput[];
    };
  };
