/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { UserConfig } from "powerlines/types/config";
import { PluginContext } from "powerlines/types/context";
import { ResolvedConfig } from "powerlines/types/resolved";
import { PrismaSchemaCreator } from "../helpers/schema-creator";
import { PrismaSchema } from "./prisma";

export interface PrismaPluginOptions {
  /**
   * The path to the Prisma schema file (PSL).
   *
   * @defaultValue "\{projectRoot\}/prisma/schema.prisma"
   */
  schema?: string;

  /**
   * The path to a custom Prisma configuration file.
   *
   * @remarks
   * This field allows the use of the "\{projectRoot\}" token to refer to the project's root directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{projectRoot\}/prisma.config.ts"
   */
  configFile?: string;

  /**
   * The path to the output file generated by the plugin.
   *
   * @remarks
   * If using the default value, the file can be imported from "powerlines:prisma/module-name". This field allows the use of the "\{builtinPath\}" token to refer to the built-in Powerlines plugins directory - the value will be replaced with the correct file path by the plugin.
   *
   * @defaultValue "\{builtinPath\}/prisma"
   */
  generatedPath?: string;

  /**
   * Additional parameters to pass to the Prisma CLI
   */
  params?: string;

  /**
   * The path to the Prisma binary
   */
  prismaPath?: string;
}

export type PrismaPluginUserConfig = UserConfig & {
  prisma?: Omit<
    PrismaPluginOptions,
    "schema" | "generatedPath" | "configFile"
  > &
    Required<
      Pick<PrismaPluginOptions, "schema" | "generatedPath" | "configFile">
    >;
};

export type PrismaPluginResolvedConfig = ResolvedConfig & {
  prisma: Omit<PrismaPluginOptions, "schema" | "generatedPath" | "configFile"> &
    Required<
      Pick<PrismaPluginOptions, "schema" | "generatedPath" | "configFile">
    >;
};

export type PrismaPluginContext<
  TResolvedConfig extends
    PrismaPluginResolvedConfig = PrismaPluginResolvedConfig
> = PluginContext<TResolvedConfig> & {
  prisma: {
    schema: PrismaSchema;
    builder: PrismaSchemaCreator;
  };
};
