/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { titleCase } from "@stryke/string-format/title-case";
import { Context } from "../../types/context";

export interface FileHeaderOptions {
  directive?: string | null;
  prettierIgnore?: boolean;
}

export function getBaseFileHeader(context: Context): string {
  return `
// Generated by ${titleCase(context.config.framework) || "Powerlines"}
${
  context.config.output?.overwrite !== false
    ? `// Do not edit this file manually - it will be overwritten automatically. Automatic overwrites can be disabled by using the \`output.overwrite\` option.`
    : `// This file was generated on ${new Date().toLocaleString()} - it will not be overwritten by ${titleCase(context.config.framework)} while the \`output.overwrite\` option is set to \`true\`.`
}
`;
}

export function getFileHeader(
  context: Context,
  options: FileHeaderOptions = {}
): string {
  const { directive = null, prettierIgnore = false } = options;

  return `/* eslint-disable */
// biome-ignore lint: disable
${prettierIgnore ? `// prettier-ignore` : ""}${directive ? `\n\n${directive}\n` : "\n"}
${getBaseFileHeader(context)}

`;
}
