/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type {
  EnvironmentContext,
  EnvironmentContextPlugin,
  EnvironmentResolvedConfig,
  HooksList,
  HooksListItem,
  Logger,
  LoggerMessage,
  LoggerOptions,
  Plugin,
  PluginConfig,
  PluginContext,
  ResolvedConfig,
  ResolvedExecutionOptions,
  SelectHookResult,
  SelectHooksOptions
} from "@powerlines/core";
import { PLUGIN_NON_HOOK_FIELDS } from "@powerlines/core/constants";
import {
  dedupeHooklist,
  isPlugin,
  isPluginConfig,
  isPluginHookField,
  mergeConfig
} from "@powerlines/core/plugin-utils";
import { resolvePackage } from "@stryke/fs/resolve";
import { deepClone } from "@stryke/helpers/deep-clone";
import { isFunction } from "@stryke/type-checks/is-function";
import { isObject } from "@stryke/type-checks/is-object";
import { isSetObject } from "@stryke/type-checks/is-set-object";
import { ArrayValues } from "@stryke/types/array";
import { uuid } from "@stryke/unique-id/uuid";
import { getConfigProps } from "../_internal/helpers/context";
import { extractHooks } from "../_internal/helpers/hooks";
import { PowerlinesContext } from "./context";
import { createPluginContext } from "./plugin-context";

export class PowerlinesEnvironmentContext<
  TResolvedConfig extends ResolvedConfig = ResolvedConfig
>
  extends PowerlinesContext<TResolvedConfig>
  implements EnvironmentContext<TResolvedConfig>
{
  /**
   * The hooks registered by plugins in this environment
   */
  #hooks: Record<string, HooksList<PluginContext<TResolvedConfig>>> = {};

  /**
   * Create a new context from the config.
   *
   * @param options - The resolved execution options.
   * @param config - The user configuration options.
   * @returns A promise that resolves to the new context.
   */
  public static async fromConfig<
    TResolvedConfig extends ResolvedConfig = ResolvedConfig
  >(
    options: ResolvedExecutionOptions,
    config: TResolvedConfig,
    environment: EnvironmentResolvedConfig
  ): Promise<PowerlinesEnvironmentContext<TResolvedConfig>> {
    const context = new PowerlinesEnvironmentContext<TResolvedConfig>(
      options,
      config,
      environment
    );
    await context.setup();

    const powerlinesPath = await resolvePackage("powerlines");
    if (!powerlinesPath) {
      throw new Error("Could not resolve `powerlines` package location.");
    }

    context.powerlinesPath = powerlinesPath;

    return context;
  }

  /**
   * The resolved environment configuration
   */
  public environment: EnvironmentResolvedConfig;

  /**
   * The list of plugins applied to this environment
   */
  public plugins: EnvironmentContextPlugin<TResolvedConfig>[] = [];

  /**
   * The unique identifier of the environment associated with this context, which can be used for logging and other purposes to distinguish between different environments in the same process.
   */
  public get id(): string {
    return this.environment.environmentId;
  }

  /**
   * The hooks registered by plugins in this environment
   */
  public get hooks(): Record<
    string,
    HooksList<PluginContext<TResolvedConfig>>
  > {
    return this.#hooks;
  }

  /**
   * Create a new logger instance
   *
   * @param options - The configuration options to use for the logger instance, which can be used to customize the appearance and behavior of the log messages generated by the logger. This is typically the name of the plugin or module that is creating the logger instance.
   * @returns A logger client instance that can be used to generate log messages with consistent formatting and metadata.
   */
  public override createLogger(
    options: LoggerOptions,
    callback?: (message: string | LoggerMessage) => void
  ): Logger {
    return super.createLogger(
      {
        ...options,
        environment: this.environment?.name
      },
      callback
    );
  }

  /**
   * Extend the base logger with additional configuration options
   *
   * @param options - The configuration options to extend the base logger with, which can be used to add additional metadata or customize the appearance of log messages generated by the logger. This is typically the name of the plugin or module that is creating the logger instance, as well as any additional metadata such as the plugin category or environment.
   * @returns A new logger client instance that extends the base logger with the provided configuration options.
   */
  public override extendLogger(options: LoggerOptions): Logger {
    return super.extendLogger({
      ...options,
      environment: this.environment?.name
    });
  }

  /**
   * Creates a clone of the current context with the same configuration and workspace settings. This can be useful for running multiple builds in parallel or for creating isolated contexts for different parts of the build process.
   *
   * @remarks
   * The cloned context will have the same configuration and workspace settings as the original context, but will have a different build ID, release ID, and timestamp. The virtual file system and caches will also be separate between the original and cloned contexts.
   *
   * @returns A promise that resolves to the cloned context.
   */
  public override async clone(): Promise<EnvironmentContext<TResolvedConfig>> {
    const context =
      (await PowerlinesEnvironmentContext.fromConfig<TResolvedConfig>(
        deepClone(this.options),
        deepClone(this.config) as TResolvedConfig,
        deepClone(this.environment) as EnvironmentResolvedConfig
      )) as any;

    return this.copyTo(context);
  }

  /**
   * Initialize the context with the provided configuration options
   */
  public override async setup(): Promise<void> {
    this.resolvedConfig = mergeConfig(
      {
        name: this.config.name,
        title: this.config.title
      },
      getConfigProps(this.environment, this.options.root, this.options.cwd),
      this.config
    ) as TResolvedConfig;

    await this.innerSetup();
  }

  public async addPlugin(plugin: Plugin<PluginContext<TResolvedConfig>>) {
    let resolvedPlugin = plugin;
    if (isFunction(plugin.applyToEnvironment)) {
      const result = (await Promise.resolve(
        plugin.applyToEnvironment(this.environment) as Promise<any>
      )) as boolean | PluginConfig<PluginContext<TResolvedConfig>>;

      if (!result || (isObject(result) && Object.keys(result).length === 0)) {
        return;
      }

      if (isPluginConfig<PluginContext<TResolvedConfig>>(result)) {
        return this.$$internal.addPlugin(result);
      }

      resolvedPlugin = isPlugin<PluginContext<TResolvedConfig>>(result)
        ? result
        : plugin;
    }

    const pluginId = uuid();
    const context = createPluginContext<TResolvedConfig>(
      pluginId,
      resolvedPlugin,
      this
    );

    this.plugins.push({
      pluginId,
      plugin: resolvedPlugin,
      context
    });

    this.#hooks = Object.entries(
      Object.keys(resolvedPlugin)
        .filter(
          key =>
            !PLUGIN_NON_HOOK_FIELDS.includes(
              key as ArrayValues<typeof PLUGIN_NON_HOOK_FIELDS>
            )
        )
        .reduce(
          (ret, key) =>
            extractHooks<TResolvedConfig>(context, ret, resolvedPlugin, key),
          this.hooks
        )
    ).reduce(
      (ret, [key, value]) => {
        if (isSetObject(value)) {
          Object.entries(value).forEach(([type, list]) => {
            ret[key] ??= {};
            ret[key][type as keyof (typeof ret)[typeof key]] =
              dedupeHooklist<PluginContext<TResolvedConfig>>(list);
          });
        }

        return ret;
      },
      {} as Record<string, HooksList<PluginContext<TResolvedConfig>>>
    );
  }

  /**
   * Retrieves the hook handlers for a specific hook name
   */
  public selectHooks<TKey extends string>(
    key: TKey,
    options?: SelectHooksOptions
  ): SelectHookResult<PluginContext<TResolvedConfig>, TKey> {
    const result = [] as SelectHookResult<PluginContext<TResolvedConfig>, TKey>;

    if (
      isPluginHookField<PluginContext<TResolvedConfig>>(key) &&
      this.hooks[key]
    ) {
      if (this.hooks[key]) {
        if (options?.order) {
          const mapHooksToResult = (
            hooksList: HooksListItem<PluginContext<TResolvedConfig>, string>[]
          ): SelectHookResult<PluginContext<TResolvedConfig>, TKey> =>
            hooksList.map(hook => {
              const plugin = this.plugins.find(
                p => p.plugin.name === hook.plugin.name
              );
              if (!plugin) {
                throw new Error(
                  `Could not find plugin context for plugin "${
                    hook.plugin.name
                  }".`
                );
              }

              return {
                handler: hook.handler,
                plugin: hook.plugin,
                context: plugin.context
              };
            });

          if (options?.order === "pre") {
            result.push(...mapHooksToResult(this.hooks[key].preOrdered ?? []));
            result.push(...mapHooksToResult(this.hooks[key].preEnforced ?? []));
          } else if (options?.order === "post") {
            result.push(...mapHooksToResult(this.hooks[key].postOrdered ?? []));
            result.push(
              ...mapHooksToResult(this.hooks[key].postEnforced ?? [])
            );
          } else {
            result.push(...mapHooksToResult(this.hooks[key].normal ?? []));
          }
        } else {
          result.push(...this.selectHooks(key, { order: "pre" }));
          result.push(...this.selectHooks(key, { order: "normal" }));
          result.push(...this.selectHooks(key, { order: "post" }));
        }
      }
    }

    return result;
  }

  protected constructor(
    options: ResolvedExecutionOptions,
    config: TResolvedConfig,
    environment: EnvironmentResolvedConfig
  ) {
    super(options);

    this.resolvedConfig = config;
    this.environment = environment;
  }

  /**
   * Creates a clone of the current context with the same configuration and workspace settings. This can be useful for running multiple builds in parallel or for creating isolated contexts for different parts of the build process.
   *
   * @remarks
   * The cloned context will have the same configuration and workspace settings as the original context, but will have a different build ID, release ID, and timestamp. The virtual file system and caches will also be separate between the original and cloned contexts.
   *
   * @returns The cloned context.
   */
  protected override copyTo(
    context: EnvironmentContext<TResolvedConfig>
  ): EnvironmentContext<TResolvedConfig> {
    context.plugins = this.plugins;

    return super.copyTo(context) as EnvironmentContext<TResolvedConfig>;
  }
}
