/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { code, Show, splitProps } from "@alloy-js/core";
import { Link } from "@alloy-js/markdown";
import { titleCase } from "@stryke/string-format/title-case";
import { isSetObject } from "@stryke/type-checks";
import { SingleLineComment } from "../../core/components/single-line-comment";
import { SourceFile, SourceFileProps } from "../../core/components/source-file";
import { usePowerlinesSafe } from "../../core/contexts/context";
import { ComponentProps, SourceFileHeaderProps } from "../../types/components";
import { FrontMatter, FrontMatterProps } from "./front-matter";

export type MarkdownFileProps = Omit<SourceFileProps, "filetype"> &
  ComponentProps &
  MarkdownFileHeaderProps;

/**
 * A base component representing a Powerlines generated markdown source file.
 *
 * @param props - The properties for the source file.
 * @returns The rendered source file component.
 */
export function MarkdownFile(props: MarkdownFileProps) {
  const [{ children, storage, frontMatter }, rest] = splitProps(props, [
    "children",
    "storage",
    "frontMatter"
  ]);

  return (
    <SourceFile
      header={<MarkdownFileHeader frontMatter={frontMatter} />}
      {...rest}
      filetype="md"
      reference={Link}
      storage={storage}>
      <Show when={Boolean(children)}>{children}</Show>
    </SourceFile>
  );
}

export type MarkdownFileHeaderProps = SourceFileHeaderProps & {
  frontMatter?: FrontMatterProps["data"];
};

/**
 * Renders the header for a Powerlines Typescript source file.
 *
 * @param props - The properties for the source file header.
 * @returns The rendered source file header.
 */
export function MarkdownFileHeader(props: MarkdownFileHeaderProps) {
  const [
    {
      children,
      disableEslint = true,
      disableBiome = true,
      disablePrettier = false,
      frontMatter
    }
  ] = splitProps(props, [
    "children",
    "disableEslint",
    "disableBiome",
    "disablePrettier",
    "frontMatter"
  ]);

  const context = usePowerlinesSafe();

  return (
    <>
      <Show
        when={isSetObject(frontMatter) && Object.keys(frontMatter).length > 0}>
        <FrontMatter data={frontMatter!} />
      </Show>
      <Show when={Boolean(disableEslint)}>
        <SingleLineComment variant="markdown">
          {"eslint-disable"}
        </SingleLineComment>
        <hbr />
      </Show>
      <Show when={Boolean(disablePrettier)}>
        <SingleLineComment variant="markdown">
          {"prettier-ignore"}
        </SingleLineComment>
        <hbr />
      </Show>
      <Show when={Boolean(disableBiome)}>
        <SingleLineComment variant="markdown">
          {"biome-ignore lint: disable"}
        </SingleLineComment>
        <hbr />
      </Show>
      <Show
        when={
          Boolean(disableEslint) ||
          Boolean(disablePrettier) ||
          Boolean(disableBiome)
        }>
        <hbr />
      </Show>
      <Show when={Boolean(children)}>
        <>
          {children}
          <hbr />
        </>
      </Show>
      <SingleLineComment variant="markdown">{`Generated by ${
        titleCase(context?.config?.framework) || "Powerlines"
      }`}</SingleLineComment>
      <hbr />
      <SingleLineComment variant="markdown">
        {code`NOTE: Do not edit this file manually - it will be overwritten automatically`}
      </SingleLineComment>
      <hbr />
    </>
  );
}
