/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

export interface NxPluginOptions {
  /**
   * Enable resolver debug logging for the plugin
   *
   * @defaultValue false
   */
  debug?: boolean;

  /**
   * Configuration options for the clean target added by the Nx plugin
   */
  clean?:
    | false
    | {
        /**
         * The name of the clean target to use when cleaning the project
         *
         * @defaultValue "clean"
         */
        targetName?: string;

        /**
         * The name of the clean configuration to use when cleaning the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the clean target depends on
         *
         * @defaultValue ["^clean"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the clean target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "testing"
          | "linting"
          | "documentation"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the clean target
         */
        outputs?: string[];

        /**
         * The executor to use for the clean target
         *
         * @defaultValue "\@powerlines/nx:clean"
         */
        executor?: string;
      };

  /**
   * Configuration options for the prepare target added by the Nx plugin
   */
  prepare?:
    | false
    | {
        /**
         * The name of the prepare target to use when preparing the project
         *
         * @defaultValue "prepare"
         */
        targetName?: string;

        /**
         * The name of the prepare configuration to use when preparing the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the prepare target depends on
         *
         * @defaultValue ["^prepare", "clean"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the prepare target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "testing"
          | "linting"
          | "documentation"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the prepare target
         */
        outputs?: string[];

        /**
         * The executor to use for the prepare target
         *
         * @defaultValue "\@powerlines/nx:prepare"
         */
        executor?: string;
      };

  /**
   * Configuration options for the lint target added by the Nx plugin
   */
  lint?:
    | false
    | {
        /**
         * The name of the lint target to use when linting the project
         *
         * @defaultValue "lint"
         */
        targetName?: string;

        /**
         * The name of the lint configuration to use when linting the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the lint target depends on
         *
         * @defaultValue ["^lint", "prepare"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the lint target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "testing"
          | "linting"
          | "documentation"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the lint target
         */
        outputs?: string[];

        /**
         * The executor to use for the lint target
         *
         * @defaultValue "\@powerlines/nx:lint"
         */
        executor?: string;
      };

  /**
   * Configuration options for the build target added by the Nx plugin
   */
  build?:
    | false
    | {
        /**
         * The name of the build target to use when building the project
         *
         * @defaultValue "build"
         */
        targetName?: string;

        /**
         * The name of the build configuration to use when building the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the build target depends on
         *
         * @defaultValue ["^build", "prepare"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the build target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "testing"
          | "linting"
          | "documentation"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the build target
         */
        outputs?: string[];

        /**
         * The executor to use for the build target
         *
         * @defaultValue "\@powerlines/nx:build"
         */
        executor?: string;
      };

  /**
   * Configuration options for the docs target added by the Nx plugin
   */
  docs?:
    | false
    | {
        /**
         * The name of the docs target to use when generating documentation for the project
         *
         * @defaultValue "docs"
         */
        targetName?: string;

        /**
         * The name of the docs configuration to use when generating documentation for the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the docs target depends on
         *
         * @defaultValue ["^docs", "build"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the docs target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "testing"
          | "linting"
          | "documentation"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the docs target
         */
        outputs?: string[];

        /**
         * The executor to use for the docs target
         *
         * @defaultValue "\@powerlines/nx:docs"
         */
        executor?: string;
      };

  /**
   * Configuration options for the deploy target added by the Nx plugin
   */
  deploy?:
    | false
    | {
        /**
         * The name of the deploy target to use when deploying the project
         *
         * @defaultValue "deploy"
         */
        targetName?: string;

        /**
         * The name of the deploy configuration to use when deploying the project
         *
         * @defaultValue "production"
         */
        defaultConfiguration?: "production" | "test" | "development";

        /**
         * An array specifying any other target identifiers the deploy target depends on
         *
         * @defaultValue ["^deploy", "build"]
         */
        dependsOn?: string[];

        /**
         * An array specifying any input files or globs to consider when determining if the deploy target needs to be re-run
         */
        inputs?:
          | string[]
          | "production"
          | "allProjectFiles"
          | "sharedGlobals"
          | "rust"
          | "typescript";

        /**
         * An array specifying the output files or globs generated by the deploy target
         */
        outputs?: string[];

        /**
         * The executor to use for the deploy target
         *
         * @defaultValue "\@powerlines/nx:deploy"
         */
        executor?: string;
      };
}
