// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ListConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
        databaseId?: string;
    };
    url: '/v1/connections';
};

export type ListConnectionsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListConnectionsError = ListConnectionsErrors[keyof ListConnectionsErrors];

export type ListConnectionsResponses = {
    /**
     * Returned list of connections.
     */
    200: {
        data: Array<{
            id: string;
            type: 'connection';
            url: string;
            name: string;
            createdAt: string;
            kind: 'postgres' | 'accelerate';
            endpoints: {
                direct?: {
                    host: string;
                    port: number;
                };
                pooled?: {
                    host: string;
                    port: number;
                };
                accelerate?: {
                    host: string;
                    port: number;
                };
            };
            directConnection?: {
                host: string;
                pass: string;
                user: string;
            } | null;
            database: {
                id: string;
                url: string;
                name: string;
            };
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListConnectionsResponse = ListConnectionsResponses[keyof ListConnectionsResponses];

export type CreateConnectionData = {
    body?: {
        databaseId: string;
        name: string;
    };
    path?: never;
    query?: never;
    url: '/v1/connections';
};

export type CreateConnectionErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Created a new connection.
     */
    201: {
        data: {
            id: string;
            type: 'connection';
            url: string;
            name: string;
            createdAt: string;
            kind: 'postgres' | 'accelerate';
            endpoints: {
                direct?: {
                    host: string;
                    port: number;
                };
                pooled?: {
                    host: string;
                    port: number;
                };
                accelerate?: {
                    host: string;
                    port: number;
                };
            };
            connectionString: string;
            directConnection?: {
                host: string;
                pass: string;
                user: string;
            } | null;
            database: {
                id: string;
                url: string;
                name: string;
            };
            host: string | null;
            pass: string | null;
            user: string | null;
        };
    };
};

export type CreateConnectionResponse = CreateConnectionResponses[keyof CreateConnectionResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}';
};

export type DeleteConnectionErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Connection with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * Deleted the connection.
     */
    204: void;
};

export type DeleteConnectionResponse = DeleteConnectionResponses[keyof DeleteConnectionResponses];

export type GetConnectionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/connections/{id}';
};

export type GetConnectionErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Connection with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetConnectionError = GetConnectionErrors[keyof GetConnectionErrors];

export type GetConnectionResponses = {
    /**
     * Returned the connection.
     */
    200: {
        data: {
            id: string;
            type: 'connection';
            url: string;
            name: string;
            createdAt: string;
            kind: 'postgres' | 'accelerate';
            endpoints: {
                direct?: {
                    host: string;
                    port: number;
                };
                pooled?: {
                    host: string;
                    port: number;
                };
                accelerate?: {
                    host: string;
                    port: number;
                };
            };
            directConnection?: {
                host: string;
                pass: string;
                user: string;
            } | null;
            database: {
                id: string;
                url: string;
                name: string;
            };
        };
    };
};

export type GetConnectionResponse = GetConnectionResponses[keyof GetConnectionResponses];

export type ListDatabasesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
        /**
         * Filter databases by project ID
         */
        projectId?: string;
    };
    url: '/v1/databases';
};

export type ListDatabasesErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Actor does not have access to the requested databases.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListDatabasesError = ListDatabasesErrors[keyof ListDatabasesErrors];

export type ListDatabasesResponses = {
    /**
     * Returns the list of databases.
     */
    200: {
        data: Array<{
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'failure' | 'provisioning' | 'ready' | 'recovering';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            } | null;
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListDatabasesResponse = ListDatabasesResponses[keyof ListDatabasesResponses];

export type CreateDatabaseData = {
    body?: {
        /**
         * ID of the project to create the database in
         */
        projectId: string;
        /**
         * Region for the database
         */
        region?: string;
        /**
         * Display name for the database
         */
        name?: string;
        /**
         * Whether this is the default database
         */
        isDefault?: boolean;
    };
    path?: never;
    query?: never;
    url: '/v1/databases';
};

export type CreateDatabaseErrors = {
    /**
     * Invalid request parameters.
     */
    400: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Actor does not have access to the specified project.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type CreateDatabaseError = CreateDatabaseErrors[keyof CreateDatabaseErrors];

export type CreateDatabaseResponses = {
    /**
     * Created a new database.
     */
    201: {
        data: {
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'failure' | 'provisioning' | 'ready' | 'recovering';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            } | null;
        };
    };
};

export type CreateDatabaseResponse = CreateDatabaseResponses[keyof CreateDatabaseResponses];

export type DeleteDatabaseData = {
    body?: never;
    path: {
        databaseId: string;
    };
    query?: never;
    url: '/v1/databases/{databaseId}';
};

export type DeleteDatabaseErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Cannot delete the default environment.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type DeleteDatabaseError = DeleteDatabaseErrors[keyof DeleteDatabaseErrors];

export type DeleteDatabaseResponses = {
    /**
     * Deleted the database successfully.
     */
    204: void;
};

export type DeleteDatabaseResponse = DeleteDatabaseResponses[keyof DeleteDatabaseResponses];

export type GetDatabaseData = {
    body?: never;
    path: {
        databaseId: string;
    };
    query?: never;
    url: '/v1/databases/{databaseId}';
};

export type GetDatabaseErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Actor does not have access to the database.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetDatabaseError = GetDatabaseErrors[keyof GetDatabaseErrors];

export type GetDatabaseResponses = {
    /**
     * Returned the database with the given ID.
     */
    200: {
        data: {
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'failure' | 'provisioning' | 'ready' | 'recovering';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            } | null;
        };
    };
};

export type GetDatabaseResponse = GetDatabaseResponses[keyof GetDatabaseResponses];

export type UpdateDatabaseData = {
    body?: {
        /**
         * New display name for the database
         */
        name?: string;
    };
    path: {
        databaseId: string;
    };
    query?: never;
    url: '/v1/databases/{databaseId}';
};

export type UpdateDatabaseErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Actor does not have access to the database.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type UpdateDatabaseError = UpdateDatabaseErrors[keyof UpdateDatabaseErrors];

export type UpdateDatabaseResponses = {
    /**
     * Updated the database.
     */
    200: {
        data: {
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'failure' | 'provisioning' | 'ready' | 'recovering';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            } | null;
        };
    };
};

export type UpdateDatabaseResponse = UpdateDatabaseResponses[keyof UpdateDatabaseResponses];

export type ListDatabaseConnectionsData = {
    body?: never;
    path: {
        databaseId: string;
    };
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
    };
    url: '/v1/databases/{databaseId}/connections';
};

export type ListDatabaseConnectionsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListDatabaseConnectionsError = ListDatabaseConnectionsErrors[keyof ListDatabaseConnectionsErrors];

export type ListDatabaseConnectionsResponses = {
    /**
     * Returned all connections for the given database.
     */
    200: {
        data: Array<{
            id: string;
            type: 'connection';
            url: string;
            name: string;
            createdAt: string;
            kind: 'postgres' | 'accelerate';
            endpoints: {
                direct?: {
                    host: string;
                    port: number;
                };
                pooled?: {
                    host: string;
                    port: number;
                };
                accelerate?: {
                    host: string;
                    port: number;
                };
            };
            directConnection?: {
                host: string;
                pass: string;
                user: string;
            } | null;
            database: {
                id: string;
                url: string;
                name: string;
            };
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListDatabaseConnectionsResponse = ListDatabaseConnectionsResponses[keyof ListDatabaseConnectionsResponses];

export type CreateDatabaseConnectionStringData = {
    body?: {
        name: string;
    };
    path: {
        databaseId: string;
    };
    query?: never;
    url: '/v1/databases/{databaseId}/connections';
};

export type CreateDatabaseConnectionStringErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type CreateDatabaseConnectionStringError = CreateDatabaseConnectionStringErrors[keyof CreateDatabaseConnectionStringErrors];

export type CreateDatabaseConnectionStringResponses = {
    /**
     * Created a new connection string for the database.
     */
    200: {
        data: {
            id: string;
            type: 'connection';
            url: string;
            name: string;
            createdAt: string;
            kind: 'postgres' | 'accelerate';
            endpoints: {
                direct?: {
                    host: string;
                    port: number;
                    connectionString: string;
                };
                pooled?: {
                    host: string;
                    port: number;
                    connectionString: string;
                };
                accelerate?: {
                    host: string;
                    port: number;
                    connectionString: string;
                };
            };
            connectionString: string;
            directConnection?: {
                host: string;
                pass: string;
                user: string;
            } | null;
            database: {
                id: string;
                url: string;
                name: string;
            };
            host: string | null;
            pass: string | null;
            user: string | null;
        };
    };
};

export type CreateDatabaseConnectionStringResponse = CreateDatabaseConnectionStringResponses[keyof CreateDatabaseConnectionStringResponses];

export type ListBackupsData = {
    body?: never;
    path: {
        databaseId: string;
    };
    query?: {
        limit?: number;
    };
    url: '/v1/databases/{databaseId}/backups';
};

export type ListBackupsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Remote database backups are not supported
     */
    422: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListBackupsError = ListBackupsErrors[keyof ListBackupsErrors];

export type ListBackupsResponses = {
    /**
     * Returned backups for the given database.
     */
    200: {
        data: Array<{
            /**
             * The unique identifier for this backup
             */
            id: string;
            /**
             * Type of backup
             */
            backupType: 'full' | 'incremental';
            /**
             * Timestamp when the backup was created
             */
            createdAt: string;
            /**
             * Total file size (in bytes) of gzipped backup files
             */
            size?: number;
            /**
             * Status of backup instance
             */
            status: 'running' | 'completed' | 'failed' | 'unknown';
            type?: 'backup';
        }>;
        meta: {
            backupRetentionDays: number;
        };
        pagination: {
            hasMore: boolean;
            limit: number | null;
        };
    };
};

export type ListBackupsResponse = ListBackupsResponses[keyof ListBackupsResponses];

export type GetDatabaseUsageMetricsData = {
    body?: never;
    path: {
        databaseId: string;
    };
    query?: {
        /**
         * Start date for metrics query. Defaults to start of current month if not provided.
         */
        startDate?: string;
        /**
         * End date for metrics query. Will be set to end of day if a future date is provided. Defaults to current date if not provided.
         */
        endDate?: string;
    };
    url: '/v1/databases/{databaseId}/usage';
};

export type GetDatabaseUsageMetricsErrors = {
    /**
     * Invalid request parameters
     */
    400: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Database with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Error occurred while fetching metrics
     */
    500: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetDatabaseUsageMetricsError = GetDatabaseUsageMetricsErrors[keyof GetDatabaseUsageMetricsErrors];

export type GetDatabaseUsageMetricsResponses = {
    /**
     * Returned usage metrics for the given database.
     */
    200: {
        period: {
            start: string;
            end: string;
        };
        metrics: {
            operations: {
                used: number;
                unit: 'ops';
            };
            storage: {
                used: number;
                unit: 'GiB';
            };
        };
        generatedAt: string;
    };
};

export type GetDatabaseUsageMetricsResponse = GetDatabaseUsageMetricsResponses[keyof GetDatabaseUsageMetricsResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
    };
    url: '/v1/projects';
};

export type ListProjectsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * Returns the list of projects.
     */
    200: {
        data: Array<{
            id: string;
            type: 'project';
            url: string;
            name: string;
            createdAt: string;
            workspace: {
                id: string;
                url: string;
                name: string;
            };
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectWithPostgresDatabaseData = {
    body?: {
        createDatabase?: boolean;
        name?: string;
        region?: 'us-east-1' | 'us-west-1' | 'eu-west-3' | 'eu-central-1' | 'ap-northeast-1' | 'ap-southeast-1';
    };
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type CreateProjectWithPostgresDatabaseErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type CreateProjectWithPostgresDatabaseError = CreateProjectWithPostgresDatabaseErrors[keyof CreateProjectWithPostgresDatabaseErrors];

export type CreateProjectWithPostgresDatabaseResponses = {
    /**
     * New project created.
     */
    201: {
        data: {
            id: string;
            type: 'project';
            url: string;
            name: string;
            createdAt: string;
            workspace: {
                id: string;
                url: string;
                name: string;
            };
            database: {
                id: string;
                type: 'database';
                url: string;
                name: string;
                status: 'provisioning' | 'ready';
                createdAt: string;
                isDefault: boolean;
                defaultConnectionId: string | null;
                connections: Array<{
                    id: string;
                    type: 'connection';
                    url: string;
                    name: string;
                    createdAt: string;
                    kind: 'postgres' | 'accelerate';
                    endpoints: {
                        direct?: {
                            host: string;
                            port: number;
                            connectionString?: string;
                        };
                        pooled?: {
                            host: string;
                            port: number;
                            connectionString?: string;
                        };
                        accelerate?: {
                            host: string;
                            port: number;
                            connectionString?: string;
                        };
                    };
                    directConnection?: {
                        host: string;
                        pass: string;
                        user: string;
                    } | null;
                    database: {
                        id: string;
                        url: string;
                        name: string;
                    };
                }>;
                region: {
                    id: string;
                    name: string;
                };
                apiKeys: Array<{
                    id: string;
                    type: 'connection';
                    url: string;
                    name: string;
                    createdAt: string;
                    kind: 'postgres' | 'accelerate';
                    endpoints: {
                        direct?: {
                            host: string;
                            port: number;
                        };
                        pooled?: {
                            host: string;
                            port: number;
                        };
                        accelerate?: {
                            host: string;
                            port: number;
                        };
                    };
                    connectionString: string;
                    directConnection?: {
                        host: string;
                        pass: string;
                        user: string;
                    } | null;
                }>;
                connectionString: string | null;
                directConnection: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
            } | null;
        };
    };
};

export type CreateProjectWithPostgresDatabaseResponse = CreateProjectWithPostgresDatabaseResponses[keyof CreateProjectWithPostgresDatabaseResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Project cannot be deleted due to existing dependencies.
     */
    400: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project with the specified ID was not found
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Project deleted.
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project with the specified ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Project retrieved.
     */
    200: {
        data: {
            id: string;
            type: 'project';
            url: string;
            name: string;
            createdAt: string;
            workspace: {
                id: string;
                url: string;
                name: string;
            };
        };
    };
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body?: {
        name?: string;
        settings?: {
            [key: string]: unknown;
        };
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type UpdateProjectErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Actor does not have access to the project.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project with the specified ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Validation failed.
     */
    422: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Project updated.
     */
    200: {
        data: {
            id: string;
            type: 'project';
            url: string;
            name: string;
            createdAt: string;
            workspace: {
                id: string;
                url: string;
                name: string;
            };
        };
    };
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type TransferProjectData = {
    body?: {
        recipientAccessToken: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/projects/{id}/transfer';
};

export type TransferProjectErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type TransferProjectError = TransferProjectErrors[keyof TransferProjectErrors];

export type TransferProjectResponses = {
    /**
     * Project transferred
     */
    204: void;
};

export type TransferProjectResponse = TransferProjectResponses[keyof TransferProjectResponses];

export type ListDatabases2Data = {
    body?: never;
    path: {
        projectId: string;
    };
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
    };
    url: '/v1/projects/{projectId}/databases';
};

export type ListDatabases2Errors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListDatabases2Error = ListDatabases2Errors[keyof ListDatabases2Errors];

export type ListDatabases2Responses = {
    /**
     * Returned the databases for the given project ID.
     */
    200: {
        data: Array<{
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'failure' | 'provisioning' | 'ready' | 'recovering';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            } | null;
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListDatabases2Response = ListDatabases2Responses[keyof ListDatabases2Responses];

export type CreateDatabase2Data = {
    body?: {
        region?: 'us-east-1' | 'us-west-1' | 'eu-west-3' | 'eu-central-1' | 'ap-northeast-1' | 'ap-southeast-1';
        name?: string;
        isDefault?: boolean;
        fromDatabase?: {
            id: string;
            /**
             * The unique identifier for this backup
             */
            backupId?: string;
        };
    };
    path: {
        projectId: string;
    };
    query?: never;
    url: '/v1/projects/{projectId}/databases';
};

export type CreateDatabase2Errors = {
    /**
     * The request is invalid due to missing or invalid parameters.
     */
    400: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Project does not belong to the service token’s workspace.
     */
    403: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type CreateDatabase2Error = CreateDatabase2Errors[keyof CreateDatabase2Errors];

export type CreateDatabase2Responses = {
    /**
     * Created a new database for the project.
     */
    201: {
        data: {
            id: string;
            type: 'database';
            url: string;
            name: string;
            status: 'provisioning' | 'ready';
            createdAt: string;
            isDefault: boolean;
            defaultConnectionId: string | null;
            connections: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                        connectionString?: string;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                        connectionString?: string;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                        connectionString?: string;
                    };
                };
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
                database: {
                    id: string;
                    url: string;
                    name: string;
                };
            }>;
            project: {
                id: string;
                url: string;
                name: string;
            };
            region: {
                id: string;
                name: string;
            };
            apiKeys: Array<{
                id: string;
                type: 'connection';
                url: string;
                name: string;
                createdAt: string;
                kind: 'postgres' | 'accelerate';
                endpoints: {
                    direct?: {
                        host: string;
                        port: number;
                    };
                    pooled?: {
                        host: string;
                        port: number;
                    };
                    accelerate?: {
                        host: string;
                        port: number;
                    };
                };
                connectionString: string;
                directConnection?: {
                    host: string;
                    pass: string;
                    user: string;
                } | null;
            }>;
            connectionString: string | null;
            directConnection: {
                host: string;
                pass: string;
                user: string;
            } | null;
        };
    };
};

export type CreateDatabase2Response = CreateDatabase2Responses[keyof CreateDatabase2Responses];

export type ListIntegrationsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
        workspaceId: string;
    };
    url: '/v1/integrations';
};

export type ListIntegrationsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListIntegrationsError = ListIntegrationsErrors[keyof ListIntegrationsErrors];

export type ListIntegrationsResponses = {
    /**
     * Returned the integrations for the given workspace.
     */
    200: {
        data: Array<{
            id: string;
            url: string;
            createdAt: string;
            scopes: Array<string>;
            client: {
                id: string;
                name: string;
                createdAt: string;
            };
            createdByUser: {
                id: string;
                email: string;
                displayName: string | null;
            };
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListIntegrationsResponse = ListIntegrationsResponses[keyof ListIntegrationsResponses];

export type DeleteIntegrationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/integrations/{id}';
};

export type DeleteIntegrationErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Integration with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type DeleteIntegrationError = DeleteIntegrationErrors[keyof DeleteIntegrationErrors];

export type DeleteIntegrationResponses = {
    /**
     * Revoked the integration tokens.
     */
    204: void;
};

export type DeleteIntegrationResponse = DeleteIntegrationResponses[keyof DeleteIntegrationResponses];

export type GetIntegrationByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/integrations/{id}';
};

export type GetIntegrationByIdErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Integration with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetIntegrationByIdError = GetIntegrationByIdErrors[keyof GetIntegrationByIdErrors];

export type GetIntegrationByIdResponses = {
    /**
     * Returned the integration.
     */
    200: {
        data: {
            id: string;
            url: string;
            createdAt: string;
            scopes: Array<string>;
            client: {
                id: string;
                name: string;
                createdAt: string;
            };
            createdByUser: {
                id: string;
                email: string;
                displayName: string | null;
            };
        };
    };
};

export type GetIntegrationByIdResponse = GetIntegrationByIdResponses[keyof GetIntegrationByIdResponses];

export type ListIntegrations2Data = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
    };
    url: '/v1/workspaces/{workspaceId}/integrations';
};

export type ListIntegrations2Errors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Workspace with the given ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListIntegrations2Error = ListIntegrations2Errors[keyof ListIntegrations2Errors];

export type ListIntegrations2Responses = {
    /**
     * Returned the integrations for the given workspace ID.
     */
    200: {
        data: Array<{
            id: string;
            url: string;
            createdAt: string;
            scopes: Array<string>;
            client: {
                id: string;
                name: string;
                createdAt: string;
            };
            createdByUser: {
                id: string;
                email: string;
                displayName: string | null;
            };
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListIntegrations2Response = ListIntegrations2Responses[keyof ListIntegrations2Responses];

export type RevokeIntegrationTokensData = {
    body?: never;
    path: {
        clientId: string;
        workspaceId: string;
    };
    query?: never;
    url: '/v1/workspaces/{workspaceId}/integrations/{clientId}';
};

export type RevokeIntegrationTokensErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Integration with the given client ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type RevokeIntegrationTokensError = RevokeIntegrationTokensErrors[keyof RevokeIntegrationTokensErrors];

export type RevokeIntegrationTokensResponses = {
    /**
     * Revoked the integration tokens.
     */
    204: void;
};

export type RevokeIntegrationTokensResponse = RevokeIntegrationTokensResponses[keyof RevokeIntegrationTokensResponses];

export type GetAllRegionsData = {
    body?: never;
    path?: never;
    query?: {
        product?: 'postgres' | 'accelerate';
    };
    url: '/v1/regions';
};

export type GetAllRegionsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetAllRegionsError = GetAllRegionsErrors[keyof GetAllRegionsErrors];

export type GetAllRegionsResponses = {
    /**
     * Returns all available regions.
     */
    200: {
        data: Array<{
            id: string;
            type: 'region';
            name: string;
            product: 'postgres' | 'accelerate';
            status?: 'available' | 'unavailable';
        }>;
    };
};

export type GetAllRegionsResponse = GetAllRegionsResponses[keyof GetAllRegionsResponses];

export type GetPrismaPostgresRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/regions/postgres';
};

export type GetPrismaPostgresRegionsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetPrismaPostgresRegionsError = GetPrismaPostgresRegionsErrors[keyof GetPrismaPostgresRegionsErrors];

export type GetPrismaPostgresRegionsResponses = {
    /**
     * Returns all available regions for Prisma Postgres.
     */
    200: {
        data: Array<{
            id: string;
            type: 'region';
            name: string;
            status: 'available' | 'unavailable';
        }>;
    };
};

export type GetPrismaPostgresRegionsResponse = GetPrismaPostgresRegionsResponses[keyof GetPrismaPostgresRegionsResponses];

export type GetPrismaAccelerateRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/regions/accelerate';
};

export type GetPrismaAccelerateRegionsErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetPrismaAccelerateRegionsError = GetPrismaAccelerateRegionsErrors[keyof GetPrismaAccelerateRegionsErrors];

export type GetPrismaAccelerateRegionsResponses = {
    /**
     * Returns all available regions for Prisma Accelerate.
     */
    200: {
        data: Array<{
            id: string;
            type: 'region';
            name: string;
        }>;
    };
};

export type GetPrismaAccelerateRegionsResponse = GetPrismaAccelerateRegionsResponses[keyof GetPrismaAccelerateRegionsResponses];

export type ListWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor for pagination
         */
        cursor?: string | null;
        /**
         * Limit for pagination
         */
        limit?: number;
    };
    url: '/v1/workspaces';
};

export type ListWorkspacesErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type ListWorkspacesError = ListWorkspacesErrors[keyof ListWorkspacesErrors];

export type ListWorkspacesResponses = {
    /**
     * Returns the list of workspaces the current token can access.
     */
    200: {
        data: Array<{
            id: string;
            type: 'workspace';
            url: string;
            name: string;
            createdAt: string;
        }>;
        pagination: {
            /**
             * Next cursor to continue pagination
             */
            nextCursor: string | null;
            /**
             * Whether there are more items to paginate
             */
            hasMore: boolean;
        };
    };
};

export type ListWorkspacesResponse = ListWorkspacesResponses[keyof ListWorkspacesResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/workspaces/{id}';
};

export type GetWorkspaceErrors = {
    /**
     * Missing or invalid authorization token.
     */
    401: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
    /**
     * Workspace with the specified ID was not found.
     */
    404: {
        error: {
            code: string;
            message: string;
            hint?: string;
        };
    };
};

export type GetWorkspaceError = GetWorkspaceErrors[keyof GetWorkspaceErrors];

export type GetWorkspaceResponses = {
    /**
     * Workspace retrieved.
     */
    200: {
        data: {
            id: string;
            type: 'workspace';
            url: string;
            name: string;
            createdAt: string;
        };
    };
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];
