/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { titleCase } from "@stryke/string-format/title-case";
import { Context } from "../../types/context";

export interface FileHeaderOptions {
  directive?: string | null;
  prettierIgnore?: boolean;
}

/**
 * Generates a file header comment with a warning about automatic overwriting.
 *
 * @param overwrite - Whether the file will be automatically overwritten. If `false`, the warning will indicate that the file will not be overwritten. If `true` or omitted, the warning will indicate that the file will be overwritten.
 * @param framework - The name of the framework to include in the warning message. Defaults to "powerlines".
 * @returns A string containing the file header warning message.
 */
export function getFileHeaderWarningText(
  overwrite = true,
  framework = "powerlines"
): string {
  return overwrite !== false
    ? `Do not edit this file manually - it will be overwritten automatically. Automatic overwrites can be disabled by using the \`output.overwrite\` option.`
    : `This file was generated on ${new Date().toLocaleString()} - it will not be overwritten by ${titleCase(framework)} while the \`output.overwrite\` option is set to \`true\`.`;
}

/**
 * Generates a file header warning message based on the provided context.
 *
 * @param context - The Powerlines context.
 * @returns A string containing the file header warning message.
 */
export function getFileHeaderWarning(context: Context): string {
  return getFileHeaderWarningText(
    context.config.output?.overwrite,
    context.config.framework?.name
  );
}

/**
 * Generates a file header comment for a generated source file, including a warning about automatic overwriting.
 *
 * @param context - The Powerlines context.
 * @param comment - The comment syntax to use for the header (e.g., `//` for JavaScript/TypeScript, `#` for Python). Defaults to `//`.
 * @returns A string containing the file header comment.
 */
export function getFileHeader(context: Context, comment = "//"): string {
  return `
${comment} Generated by ${titleCase(context.config.framework?.name) || "Powerlines"}
${comment} ${getFileHeaderWarning(context)}
`;
}

/**
 * Generates a file header comment for a generated TypeScript source file, including a warning about automatic overwriting.
 *
 * @param context - The Powerlines context.
 * @param options - Additional options for generating the file header, such as a directive to include and whether to add a Prettier ignore comment.
 * @returns A string containing the file header comment for a TypeScript file.
 */
export function getTypescriptFileHeader(
  context: Context,
  options: FileHeaderOptions = {}
): string {
  const { directive = null, prettierIgnore = false } = options;

  return `/* eslint-disable */
// biome-ignore lint: disable
${prettierIgnore ? `// prettier-ignore` : ""}${directive ? `\n\n${directive}\n` : "\n"}
${getFileHeader(context)}

`;
}
