/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { getLogFn, getLogLevel } from "@storm-software/config-tools/logger";
import { getColor } from "@storm-software/config-tools/utilities/colors";
import { noop } from "@stryke/helpers/noop";
import { kebabCase } from "@stryke/string-format/kebab-case";
import { titleCase } from "@stryke/string-format/title-case";
import { isSetObject } from "@stryke/type-checks/is-set-object";
import { isSetString } from "@stryke/type-checks/is-set-string";
import chalk from "chalk";
import { DEFAULT_ENVIRONMENT } from "../constants/environments";
import { resolveLogLevel } from "../plugin-utils";
import type { LogFn, LogFnConfig } from "../types/log";

const BADGE_COLORS = [
  "#00A0DD",
  "#6FCE4E",
  "#FBBF24",
  "#F43F5E",
  "#3B82F6",
  "#A855F7",
  "#469592",
  "#288EDF",
  "#D8B4FE",
  "#10B981",
  "#EF4444",
  "#F0EC56",
  "#F472B6",
  "#22D3EE",
  "#EAB308",
  "#84CC16",
  "#F87171",
  "#0EA5E9",
  "#D946EF",
  "#FACC15",
  "#34D399",
  "#8B5CF6"
] as const;

/**
 * Generate a consistent color based on the input text.
 *
 * @param text - The input text to generate the color from.
 * @return A hexadecimal color string.
 */
export const getTextColor = (text: string): string => {
  return (
    BADGE_COLORS[
      text
        .split("")
        .map(char => char.charCodeAt(0))
        .reduce((ret, charCode) => ret + charCode, 0) % BADGE_COLORS.length
    ] || BADGE_COLORS[0]
  );
};

/**
 * Generate a consistent color based on the input text.
 *
 * @param text - The input text to generate the color from.
 * @return A hexadecimal color string.
 */
export const colorText = (text: string): string => {
  const title = titleCase(text);

  return chalk.hex(getTextColor(title))(title);
};

/**
 * Generate a consistent color based on the input text.
 *
 * @param text - The input text to generate the color from.
 * @return A hexadecimal color string.
 */
export const colorBackground = (text: string): string => {
  const title = titleCase(text);

  return chalk.inverse.hex(getTextColor(title))(` ${title} `);
};

/**
 * Create a logging function with a specific name and options.
 *
 * @param config - The options to configure the logging function, including the source, command, environment, plugin, log level, custom logger, and colors. These options can be used to customize the appearance and behavior of the log messages generated by the logging function.
 * @returns A logging function.
 */
export const createLogFn = (config: LogFnConfig): LogFn => {
  if (config.logLevel === "silent") {
    return noop;
  }

  const logLevel = resolveLogLevel(config.logLevel || "info", config.mode);

  return (meta, ...args) =>
    getLogFn(getLogLevel(isSetString(meta) ? meta : meta.level), {
      ...config,
      logLevel:
        logLevel[
          (isSetObject(meta) && isSetString(meta.category)
            ? meta.category
            : isSetString(meta)
              ? meta
              : "general") as keyof typeof logLevel
        ]
    })(
      `${
        config.source
          ? chalk.bold.hex(getColor("brand", config))(kebabCase(config.source))
          : ""
      }${
        config.command
          ? chalk.hex(getColor("brand", config))(` (${config.command})`)
          : ""
      }${config.source ? chalk.grey(" > ") : ""}${
        config.plugin &&
        (!config.source ||
          kebabCase(config.plugin) !== kebabCase(config.source))
          ? `${chalk.bold.hex(getColor("brand", config))(
              kebabCase(config.plugin)
            )}${chalk.grey(" > ")}`
          : ""
      }${
        config.environment && config.environment !== DEFAULT_ENVIRONMENT
          ? `${chalk.bold.hex(getColor("brand", config))(
              kebabCase(config.environment)
            )}${chalk.grey(" > ")}`
          : ""
      }${args.join(" ")} `.trim()
    );
};

/**
 * Extend a logging function with a specific name, adding a colored badge to the log output.
 *
 * @param logFn - The original logging function to extend.
 * @param config - The overlay metadata to use for the badge in the log output.
 * @returns A new logging function that includes the badge in its output.
 */
export const extendLogFn = (logFn: LogFn, config: LogFnConfig): LogFn => {
  return (meta, ...args) =>
    config.source || config.category
      ? logFn(
          isSetObject(meta)
            ? { ...config, ...meta }
            : { ...config, level: meta },
          `${colorBackground(String(config.source || config.category))} ${args
            .filter(Boolean)
            .map(arg => String(arg).trim())
            .join(" ")} `
        )
      : logFn(meta, ...args);
};
