/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { Children, computed, Show, splitProps } from "@alloy-js/core";
import { findFileExtension } from "@stryke/path/file-path-fns";
import { titleCase } from "@stryke/string-format/title-case";
import { getFileHeaderWarning } from "powerlines/utils";
import {
  InfrastructureFile,
  InfrastructureFileProps
} from "../../core/components/infrastructure-file";
import { SingleLineComment } from "../../core/components/single-line-comment";
import { usePowerlines } from "../../core/contexts/context";
import { ComponentProps } from "../../types/components";

export type HCLFileProps = Omit<
  InfrastructureFileProps,
  "header" | "filetype"
> &
  ComponentProps & {
    header?: Children;
    filetype?: "hcl" | "tf" | `${string}.hcl` | `${string}.tf`;
  };

/**
 * A base component representing a Powerlines generated HCL source file.
 *
 * @param props - The properties for the source file.
 * @returns The rendered source file component.
 */
export function HCLFile(props: HCLFileProps) {
  const [{ children, storage, header, filetype: _filetype, id }, rest] =
    splitProps(props, ["children", "storage", "header", "filetype", "id"]);

  const filetype = computed(() => _filetype || findFileExtension(id) || "hcl");

  return (
    <InfrastructureFile
      header={<HCLFileHeader>{header}</HCLFileHeader>}
      {...rest}
      id={id}
      filetype={filetype.value}
      storage={storage || "fs"}>
      <Show when={Boolean(children)}>{children}</Show>
    </InfrastructureFile>
  );
}

/**
 * Renders the header for a Powerlines HCL source file.
 *
 * @param props - The properties for the source file header.
 * @returns The rendered source file header.
 */
export function HCLFileHeader(props: ComponentProps) {
  const [{ children }] = splitProps(props, ["children"]);

  const context = usePowerlines();

  return (
    <>
      <Show when={Boolean(children)}>
        <>
          {children}
          <hbr />
        </>
      </Show>
      <SingleLineComment variant="hcl">{`Generated by ${
        titleCase(context?.config?.framework?.name) || "Powerlines"
      }`}</SingleLineComment>
      <hbr />
      <SingleLineComment variant="hcl">
        {getFileHeaderWarning(context)}
      </SingleLineComment>
      <hbr />
    </>
  );
}
