/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { LogMeta } from "@powerlines/core";
import { Asyncify } from "@stryke/types/async";
import { MaybePromise } from "@stryke/types/base";
import { BirpcReturn, ProxifiedRemoteFunctions } from "birpc";
import { RpcStreamingClientHost } from "devframe/client";
import type { RpcCacheManager, RpcFunctionsCollector } from "devframe/rpc";
import type {
  ConnectionMeta,
  EventEmitter,
  RpcSharedStateHost
} from "devframe/types";
import {
  DevToolsRpcClientFunctions,
  DevToolsRpcServerFunctions
} from "devframe/types";

export interface RpcPayloadMetadata {
  /**
   * A unique identifier for correlating related Rpc messages, which can be used to group messages that belong to the same logical operation or workflow across different parts of the system. This is a required field and should be generated by the sender of the message.
   */
  messageId: string;
  /**
   * The type of the Rpc message, which indicates the purpose of the message and how it should be handled by the receiving end. This is a required field and must be one of the predefined values in the IpcMessageType enum.
   */
  type: string;
  /**
   * The timestamp when the Rpc message was created, represented as the number of milliseconds since the Unix epoch.
   */
  timestamp: number;
  /**
   * A unique identifier for the current execution instance, which can be used for logging and other purposes to distinguish between different executions in the same process.
   */
  executionId?: string;
  /**
   * The zero-based index of the current execution within the sequence of executions in the same process.
   */
  configIndex?: number;
  /**
   * Optional environment identifier to specify the context or environment in which the message is being processed.
   */
  environment?: string;
}

export interface RpcPayloadEnvelop<TPayload> extends RpcPayloadMetadata {
  /**
   * The payload data associated with the Rpc message, typed according to the message type.
   */
  payload: TPayload;
}

export type RpcFunction = (payload: any) => MaybePromise<any>;
export type RpcFunctions = Record<string, RpcFunction>;

export type InputRpcFunction = (envelop: RpcPayloadEnvelop<any>) => any;
export type InputRpcFunctions = Record<string, InputRpcFunction>;

export type WrappedRpcFunction = (
  envelop: RpcPayloadEnvelop<any>
) => Promise<any>;
export type WrappedRpcFunctions = Record<string, WrappedRpcFunction>;

export type ExtractRpcFunction<TFunction extends WrappedRpcFunction> = (
  payload: Parameters<TFunction>[0]["payload"]
) => ReturnType<Asyncify<TFunction>>;

export type ExtractRpcFunctions<TFunctions extends WrappedRpcFunctions> = {
  [TKey in keyof TFunctions]: ExtractRpcFunction<TFunctions[TKey]>;
};

export type WrapRpcFunction<TFunction extends RpcFunction> = (
  envelop: RpcPayloadEnvelop<Parameters<TFunction>[0]>
) => ReturnType<TFunction> extends Promise<infer A> ? A : ReturnType<TFunction>;

export type WrapRpcFunctions<TFunctions extends RpcFunctions> = {
  [TKey in keyof TFunctions]: WrapRpcFunction<TFunctions[TKey]>;
};

export type RpcClientRemoteFunctions<TFunctions extends WrappedRpcFunctions> =
  ProxifiedRemoteFunctions<ExtractRpcFunctions<TFunctions>>;

/**
 * Payload for write log Rpc messages.
 */
export interface LogPayload {
  /**
   * Metadata associated with the log message, excluding fields that are automatically added by the engine such as executionId, configIndex, environment, and timestamp. This can include custom fields relevant to the log entry, such as category, name, command, hook, plugin, and source.
   */
  meta: LogMeta;

  /**
   * The log message content, which can be a string or an array of strings representing the log entry. This field is required and should contain the actual message to be logged.
   */
  message: string;
}

export interface RpcServerFunctions extends DevToolsRpcServerFunctions {
  // eslint-disable-next-line ts/naming-convention
  "powerlines:log": (payload: LogPayload) => void;
}

export interface RpcClientFunctions extends DevToolsRpcClientFunctions {}

export interface RpcContext {
  /**
   * The Rpc client to interact with the server
   */
  readonly rpc: RpcClient;
}

export type RpcClientHost = RpcFunctionsCollector<
  RpcClientFunctions,
  RpcContext
>;

export type RpcClientCall = BirpcReturn<
  RpcServerFunctions,
  RpcClientFunctions
>["$call"];
export type RpcClientCallEvent = BirpcReturn<
  RpcServerFunctions,
  RpcClientFunctions
>["$callEvent"];
export type RpcClientCallOptional = BirpcReturn<
  RpcServerFunctions,
  RpcClientFunctions
>["$callOptional"];

export interface RpcClientEvents {
  // eslint-disable-next-line ts/naming-convention
  "rpc:is-trusted:updated": (isTrusted: boolean) => void;
}

export interface RpcClient {
  /**
   * The events of the client
   */
  events: EventEmitter<RpcClientEvents>;

  /**
   * Whether the client is trusted
   */
  readonly isTrusted: boolean | null;

  /**
   * The connection meta
   */
  readonly connectionMeta: ConnectionMeta;

  /**
   * Return a promise that resolves when the client is trusted
   *
   * Rejects with an error if the timeout is reached
   *
   * @param timeout - The timeout in milliseconds, default to 60 seconds
   */
  ensureTrusted: (timeout?: number) => Promise<boolean>;

  /**
   * Request trust from the server
   */
  requestTrust: () => Promise<boolean>;

  /**
   * Request trust from the server using a specific auth token.
   * Updates the stored token and re-requests trust without reloading the page.
   */
  requestTrustWithToken: (token: string) => Promise<boolean>;

  /**
   * Call a Rpc function on the server
   */
  call: RpcClientCall;

  /**
   * Call a Rpc event on the server, and does not expect a response
   */
  callEvent: RpcClientCallEvent;

  /**
   * Call a Rpc optional function on the server
   */
  callOptional: RpcClientCallOptional;

  /**
   * The client Rpc host
   */
  client: RpcClientHost;

  /**
   * The shared state host
   */
  sharedState: RpcSharedStateHost;

  /**
   * The streaming channel host. Subscribe to a server-side stream by
   * channel + id; the returned reader is both `AsyncIterable<T>` and
   * exposes `.readable: ReadableStream<T>` for `pipeTo` consumption.
   */
  streaming: RpcStreamingClientHost;

  /**
   * The Rpc cache manager
   */
  cacheManager: RpcCacheManager;
}
