/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { Children } from "@alloy-js/core";
import { code, For, Show, splitProps } from "@alloy-js/core";
import { titleCase } from "@stryke/string-format/title-case";
import { isSetObject } from "@stryke/type-checks";
import { getFileHeaderWarning } from "powerlines/utils";
import { SingleLineComment } from "../../core/components/single-line-comment";
import { SourceFile, SourceFileProps } from "../../core/components/source-file";
import { usePowerlinesSafe } from "../../core/contexts/context";
import { ComponentProps, SourceFileHeaderProps } from "../../types/components";

export interface YamlData {
  [key: string]: string | number | boolean | YamlData | YamlData[];
}

interface YamlFileDataItemProps {
  value: string | number | boolean | YamlData | YamlData[];
  key?: string;
}

function YamlFileDataItem({ key, value }: YamlFileDataItemProps) {
  return (
    <>
      <Show when={Boolean(key)}>{code`${key}:`}</Show>
      <Show
        when={
          typeof value === "string" ||
          typeof value === "number" ||
          typeof value === "boolean"
        }>
        {code`  ${String(value)}`}
      </Show>
      <Show when={isSetObject(value) && !Array.isArray(value)}>
        <For each={Object.entries(value as YamlData)}>
          {([nestedKey, nestedValue]) => (
            <YamlFileDataItem key={nestedKey} value={nestedValue} />
          )}
        </For>
      </Show>
      <Show when={Array.isArray(value)}>
        <For each={value as YamlData[]}>
          {item => <YamlFileDataItem value={item} />}
        </For>
      </Show>
    </>
  );
}

interface YamlFileDataProps {
  data?: YamlData;
}

function YamlFileData({ data }: YamlFileDataProps) {
  return (
    <>
      <Show when={Boolean(data)}>
        <For each={Object.entries(data ?? {})}>
          {([key, value]) => <YamlFileDataItem key={key} value={value} />}
        </For>
      </Show>
    </>
  );
}

export type YamlFileProps = Omit<SourceFileProps, "filetype"> &
  ComponentProps & {
    header?: Children;
    data?: YamlData;
  };

/**
 * A base component representing a Powerlines generated YAML source file.
 *
 * @remarks
 * The file content can be provided either through the `data` prop, which accepts a nested object representing the YAML structure, or through the `children` prop, which allows for custom YAML content to be rendered. The `header` prop can be used to provide custom header content for the YAML file, which is rendered above the generated file header warning and generation comment.
 *
 * @param props - The properties for the source file.
 * @returns The rendered source file component.
 */
export function YamlFile(props: YamlFileProps) {
  const [{ children, path, data, header }, rest] = splitProps(props, [
    "children",
    "path",
    "data",
    "header"
  ]);

  return (
    <SourceFile
      {...rest}
      path={path}
      header={<YamlFileHeader>{header}</YamlFileHeader>}
      filetype="yaml">
      <Show when={Boolean(data)}>
        <YamlFileData data={data} />
      </Show>
      <Show when={Boolean(children)}>
        <>
          {children}
          <hbr />
        </>
      </Show>
    </SourceFile>
  );
}

/**
 * Renders the header for a Powerlines YAML source file.
 *
 * @param props - The properties for the source file header.
 * @returns The rendered source file header.
 */
export function YamlFileHeader(props: SourceFileHeaderProps) {
  const { children } = props;

  const context = usePowerlinesSafe();

  return (
    <>
      <Show when={Boolean(children)}>
        <>
          {children}
          <hbr />
        </>
      </Show>
      <SingleLineComment>{`Generated by ${
        titleCase(context?.config?.framework?.name) || "Powerlines"
      }`}</SingleLineComment>
      <hbr />
      <SingleLineComment variant="yaml">
        {getFileHeaderWarning(context!)}
      </SingleLineComment>
      <hbr />
    </>
  );
}
