/* -------------------------------------------------------------------

                   ⚡ Storm Software - Powerlines

 This code was released as part of the Powerlines project. Powerlines
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/powerlines.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/powerlines
 Documentation:            https://docs.stormsoftware.com/projects/powerlines
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import { LogLevelLabel } from "@storm-software/config-tools/types";

export enum IpcMessageType {
  ACTIVITY = "activity",
  WRITE_LOG = "write-log",
  UPDATE_COMMAND = "update-command",
  UPDATE_HOOK = "update-hook",
  UPDATE_PLUGIN = "update-plugin"
}

export interface IpcMessage<
  TMessageType extends IpcMessageType = IpcMessageType,
  TPayload extends Record<string, any> | undefined =
    | Record<string, any>
    | undefined
> {
  /**
   * A unique identifier for correlating related IPC messages, which can be used to group messages that belong to the same logical operation or workflow across different parts of the system. This is a required field and should be generated by the sender of the message.
   */
  id: string;
  /**
   * The type of the IPC message, which indicates the purpose of the message and how it should be handled by the receiving end. This is a required field and must be one of the predefined values in the IpcMessageType enum.
   */
  type: TMessageType;
  /**
   * The timestamp when the IPC message was created, represented as the number of milliseconds since the Unix epoch.
   */
  timestamp: number;
  /**
   * A unique identifier for the current execution instance, which can be used for logging and other purposes to distinguish between different executions in the same process.
   */
  executionId: string;
  /**
   * The zero-based index of the current execution within the sequence of executions in the same process.
   */
  executionIndex: number;
  /**
   * Optional environment identifier to specify the context or environment in which the message is being processed.
   */
  environment?: string;
  /**
   * The payload data associated with the IPC message, typed according to the message type.
   */
  payload: TPayload;
}

/**
 * Payload for write log IPC messages.
 */
export interface WriteLogMessagePayload {
  /**
   * The log level label indicating the severity of the log message.
   */
  level: LogLevelLabel;
  /**
   * The name of the logger or source of the log message, which can be used to identify the origin of the log entry.
   */
  source?: string;
  /**
   * Optional environment name to specify the context or environment in which the log message is being generated.
   */
  environment?: string;
  /**
   * Optional plugin name to specify the source plugin of the log message.
   */
  plugin?: string;
  /**
   * Array of arguments to be logged as strings.
   */
  args: string[];
}

/**
 * Payload for update command IPC messages.
 */
export interface UpdateCommandMessagePayload {
  /**
   * The command identifier to be updated.
   */
  command: string;
}

/**
 * Payload for update hook IPC messages.
 */
export interface UpdateHookMessagePayload {
  /**
   * The hook identifier to be updated.
   */
  hook: string;
  /**
   * The order in which the hook should be executed: "pre" (before), "post" (after), or "normal".
   */
  order: "pre" | "post" | "normal";
}

/**
 * Payload for update plugin IPC messages.
 */
export interface UpdatePluginMessagePayload {
  /**
   * The plugin identifier to be updated.
   */
  plugin: string;
}

/**
 * IPC message for activity notifications with no payload.
 */
export type ActivityIpcMessage = IpcMessage<IpcMessageType.ACTIVITY, undefined>;

/**
 * IPC message for write log operations.
 */
export type WriteLogIpcMessage = IpcMessage<
  IpcMessageType.WRITE_LOG,
  WriteLogMessagePayload
>;

/**
 * IPC message for command updates.
 */
export type UpdateCommandIpcMessage = IpcMessage<
  IpcMessageType.UPDATE_COMMAND,
  UpdateCommandMessagePayload
>;

/**
 * IPC message for hook updates.
 */
export type UpdateHookIpcMessage = IpcMessage<
  IpcMessageType.UPDATE_HOOK,
  UpdateHookMessagePayload
>;

/**
 * IPC message for plugin updates.
 */
export type UpdatePluginIpcMessage = IpcMessage<
  IpcMessageType.UPDATE_PLUGIN,
  UpdatePluginMessagePayload
>;

/**
 * Union type representing all possible worker IPC messages.
 */
export type WorkerIpcMessage =
  | ActivityIpcMessage
  | WriteLogIpcMessage
  | UpdateCommandIpcMessage
  | UpdateHookIpcMessage
  | UpdatePluginIpcMessage;
