/* eslint-disable */
// biome-ignore lint: disable
// Generated by storm-capnpc
// Note: Do not edit this file manually - it will be overwritten automatically
import * as $ from "@stryke/capnp";
export const _capnpFileId = BigInt("0xa56c61324b9d6e49");
export class FileMetadata_KeyValuePair extends $.Struct {
  public static override readonly _capnp = {
    displayName: "KeyValuePair",
    id: "eabb26cf58b2a14c",
    size: new $.ObjectSize(0, 2),
  };
  get key(): string {
    return $.utils.getText(0, this);
  }
  set key(value: string) {
    $.utils.setText(0, value, this);
  }
  get value(): string {
    return $.utils.getText(1, this);
  }
  set value(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileMetadata_KeyValuePair_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class FileMetadata extends $.Struct {
  static readonly KeyValuePair = FileMetadata_KeyValuePair;
  public static override readonly _capnp = {
    displayName: "FileMetadata",
    id: "8e2cab5d7e28c7b3",
    size: new $.ObjectSize(0, 4),
    defaultVariant: "normal"
  };
  static _Properties: $.ListCtor<FileMetadata_KeyValuePair>;
  /**
* The variant of the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* The output mode of the file.
*
*/
  get variant(): string {
    return $.utils.getText(1, this, FileMetadata._capnp.defaultVariant);
  }
  set variant(value: string) {
    $.utils.setText(1, value, this);
  }
  /**
* Additional metadata associated with the file.
*
*/
  get mode(): string {
    return $.utils.getText(2, this);
  }
  set mode(value: string) {
    $.utils.setText(2, value, this);
  }
  _adoptProperties(value: $.Orphan<$.List<FileMetadata_KeyValuePair>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownProperties(): $.Orphan<$.List<FileMetadata_KeyValuePair>> {
    return $.utils.disown(this.properties);
  }
  get properties(): $.List<FileMetadata_KeyValuePair> {
    return $.utils.getList(3, FileMetadata._Properties, this);
  }
  _hasProperties(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initProperties(length: number): $.List<FileMetadata_KeyValuePair> {
    return $.utils.initList(3, FileMetadata._Properties, length, this);
  }
  set properties(value: $.List<FileMetadata_KeyValuePair>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  public override toString(): string { return "FileMetadata_" + super.toString(); }
}
/**
* A virtual (or actual) path to the file in the file system.
*
*/
export class FileIdentifier extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileIdentifier",
    id: "e12b8732389d7406",
    size: new $.ObjectSize(0, 2),
  };
  /**
* An additional identifier for the file.
*
*/
  get path(): string {
    return $.utils.getText(0, this);
  }
  set path(value: string) {
    $.utils.setText(0, value, this);
  }
  get id(): string {
    return $.utils.getText(1, this);
  }
  set id(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileIdentifier_" + super.toString(); }
}
/**
* A virtual (or actual) path to the file in the file system.
*
*/
export class FileData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileData",
    id: "fa6725c8a360f9a2",
    size: new $.ObjectSize(0, 2),
  };
  /**
* The contents of the file.
*
*/
  get path(): string {
    return $.utils.getText(0, this);
  }
  set path(value: string) {
    $.utils.setText(0, value, this);
  }
  get content(): string {
    return $.utils.getText(1, this);
  }
  set content(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileData_" + super.toString(); }
}
export class FileSystemData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileSystemData",
    id: "aaa72a672ac0732f",
    size: new $.ObjectSize(0, 3),
  };
  static _Ids: $.ListCtor<FileIdentifier>;
  static _Metadata: $.ListCtor<FileMetadata>;
  static _Files: $.ListCtor<FileData>;
  _adoptIds(value: $.Orphan<$.List<FileIdentifier>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownIds(): $.Orphan<$.List<FileIdentifier>> {
    return $.utils.disown(this.ids);
  }
  get ids(): $.List<FileIdentifier> {
    return $.utils.getList(0, FileSystemData._Ids, this);
  }
  _hasIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initIds(length: number): $.List<FileIdentifier> {
    return $.utils.initList(0, FileSystemData._Ids, length, this);
  }
  set ids(value: $.List<FileIdentifier>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptMetadata(value: $.Orphan<$.List<FileMetadata>>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownMetadata(): $.Orphan<$.List<FileMetadata>> {
    return $.utils.disown(this.metadata);
  }
  get metadata(): $.List<FileMetadata> {
    return $.utils.getList(1, FileSystemData._Metadata, this);
  }
  _hasMetadata(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initMetadata(length: number): $.List<FileMetadata> {
    return $.utils.initList(1, FileSystemData._Metadata, length, this);
  }
  set metadata(value: $.List<FileMetadata>) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptFiles(value: $.Orphan<$.List<FileData>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownFiles(): $.Orphan<$.List<FileData>> {
    return $.utils.disown(this.files);
  }
  get files(): $.List<FileData> {
    return $.utils.getList(2, FileSystemData._Files, this);
  }
  _hasFiles(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initFiles(length: number): $.List<FileData> {
    return $.utils.initList(2, FileSystemData._Files, length, this);
  }
  set files(value: $.List<FileData>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  public override toString(): string { return "FileSystemData_" + super.toString(); }
}
FileMetadata._Properties = $.CompositeList(FileMetadata_KeyValuePair);
FileSystemData._Ids = $.CompositeList(FileIdentifier);
FileSystemData._Metadata = $.CompositeList(FileMetadata);
FileSystemData._Files = $.CompositeList(FileData);
