/* eslint-disable */
// biome-ignore lint: disable
// Generated by storm-capnpc
// Note: Do not edit this file manually - it will be overwritten automatically
import * as $ from "@stryke/capnp";
export const _capnpFileId = BigInt("0xa56c61324b9d6e49");
export const FileType = {
  NORMAL: 0,
  BUILTIN: 1,
  ENTRY: 2,
  CHUNK: 3,
  PREBUILT: 4,
  ASSET: 5
} as const;
export type FileType = (typeof FileType)[keyof typeof FileType];
export const PreserveSignatureType = {
  STRICT: 0,
  ALLOW_EXTENSION: 1,
  EXPORTS_ONLY: 2
} as const;
export type PreserveSignatureType = (typeof PreserveSignatureType)[keyof typeof PreserveSignatureType];
export class FileMetadata_KeyValuePair extends $.Struct {
  public static override readonly _capnp = {
    displayName: "KeyValuePair",
    id: "eabb26cf58b2a14c",
    size: new $.ObjectSize(0, 2),
  };
  get key(): string {
    return $.utils.getText(0, this);
  }
  set key(value: string) {
    $.utils.setText(0, value, this);
  }
  get value(): string {
    return $.utils.getText(1, this);
  }
  set value(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileMetadata_KeyValuePair_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class FileMetadata extends $.Struct {
  static readonly KeyValuePair = FileMetadata_KeyValuePair;
  public static override readonly _capnp = {
    displayName: "FileMetadata",
    id: "8e2cab5d7e28c7b3",
    size: new $.ObjectSize(8, 4),
    defaultType: "normal"
  };
  static _Properties: $.ListCtor<FileMetadata_KeyValuePair>;
  /**
* The type of the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* The output mode of the file.
*
*/
  get type(): string {
    return $.utils.getText(1, this, FileMetadata._capnp.defaultType);
  }
  set type(value: string) {
    $.utils.setText(1, value, this);
  }
  /**
* The timestamp representing the file's creation date.
*
*/
  get mode(): string {
    return $.utils.getText(2, this);
  }
  set mode(value: string) {
    $.utils.setText(2, value, this);
  }
  /**
* Additional metadata associated with the file.
*
*/
  get timestamp(): number {
    return $.utils.getUint32(0, this);
  }
  set timestamp(value: number) {
    $.utils.setUint32(0, value, this);
  }
  _adoptProperties(value: $.Orphan<$.List<FileMetadata_KeyValuePair>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownProperties(): $.Orphan<$.List<FileMetadata_KeyValuePair>> {
    return $.utils.disown(this.properties);
  }
  get properties(): $.List<FileMetadata_KeyValuePair> {
    return $.utils.getList(3, FileMetadata._Properties, this);
  }
  _hasProperties(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initProperties(length: number): $.List<FileMetadata_KeyValuePair> {
    return $.utils.initList(3, FileMetadata._Properties, length, this);
  }
  set properties(value: $.List<FileMetadata_KeyValuePair>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  public override toString(): string { return "FileMetadata_" + super.toString(); }
}
/**
* An identifier for the file.
*
*/
export class FileId extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileId",
    id: "990d6a471072f997",
    size: new $.ObjectSize(0, 2),
  };
  /**
* A virtual (or actual) path to the file in the file system.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get path(): string {
    return $.utils.getText(1, this);
  }
  set path(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileId_" + super.toString(); }
}
/**
* An identifier for the file.
*
*/
export class FileData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileData",
    id: "fa6725c8a360f9a2",
    size: new $.ObjectSize(0, 2),
  };
  /**
* A virtual (or actual) path to the file in the file system.
*
*/
  get path(): string {
    return $.utils.getText(0, this);
  }
  set path(value: string) {
    $.utils.setText(0, value, this);
  }
  get code(): string {
    return $.utils.getText(1, this);
  }
  set code(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileData_" + super.toString(); }
}
export class FileSystem extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileSystem",
    id: "ae0c23d43e56abcf",
    size: new $.ObjectSize(0, 3),
  };
  static _Ids: $.ListCtor<FileId>;
  static _Files: $.ListCtor<FileData>;
  static _Metadata: $.ListCtor<FileMetadata>;
  _adoptIds(value: $.Orphan<$.List<FileId>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownIds(): $.Orphan<$.List<FileId>> {
    return $.utils.disown(this.ids);
  }
  get ids(): $.List<FileId> {
    return $.utils.getList(0, FileSystem._Ids, this);
  }
  _hasIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initIds(length: number): $.List<FileId> {
    return $.utils.initList(0, FileSystem._Ids, length, this);
  }
  set ids(value: $.List<FileId>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptFiles(value: $.Orphan<$.List<FileData>>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownFiles(): $.Orphan<$.List<FileData>> {
    return $.utils.disown(this.files);
  }
  get files(): $.List<FileData> {
    return $.utils.getList(1, FileSystem._Files, this);
  }
  _hasFiles(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initFiles(length: number): $.List<FileData> {
    return $.utils.initList(1, FileSystem._Files, length, this);
  }
  set files(value: $.List<FileData>) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptMetadata(value: $.Orphan<$.List<FileMetadata>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownMetadata(): $.Orphan<$.List<FileMetadata>> {
    return $.utils.disown(this.metadata);
  }
  get metadata(): $.List<FileMetadata> {
    return $.utils.getList(2, FileSystem._Metadata, this);
  }
  _hasMetadata(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initMetadata(length: number): $.List<FileMetadata> {
    return $.utils.initList(2, FileSystem._Metadata, length, this);
  }
  set metadata(value: $.List<FileMetadata>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  public override toString(): string { return "FileSystem_" + super.toString(); }
}
FileMetadata._Properties = $.CompositeList(FileMetadata_KeyValuePair);
FileSystem._Ids = $.CompositeList(FileId);
FileSystem._Files = $.CompositeList(FileData);
FileSystem._Metadata = $.CompositeList(FileMetadata);
