/* eslint-disable */
// biome-ignore lint: disable
// Generated by storm-capnpc
// Note: Do not edit this file manually - it will be overwritten automatically
import * as $ from "@stryke/capnp";
export const _capnpFileId = BigInt("0xa56c61324b9d6e49");
export const FileType = {
  NORMAL: 0,
  BUILTIN: 1,
  ENTRY: 2,
  CHUNK: 3,
  PREBUILT: 4,
  ASSET: 5
} as const;
export type FileType = (typeof FileType)[keyof typeof FileType];
export const PreserveSignatureType = {
  STRICT: 0,
  ALLOW_EXTENSION: 1,
  EXPORTS_ONLY: 2
} as const;
export type PreserveSignatureType = (typeof PreserveSignatureType)[keyof typeof PreserveSignatureType];
export class FileMetadata_KeyValuePair extends $.Struct {
  public static override readonly _capnp = {
    displayName: "KeyValuePair",
    id: "eabb26cf58b2a14c",
    size: new $.ObjectSize(0, 2),
  };
  get key(): string {
    return $.utils.getText(0, this);
  }
  set key(value: string) {
    $.utils.setText(0, value, this);
  }
  get value(): string {
    return $.utils.getText(1, this);
  }
  set value(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileMetadata_KeyValuePair_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class FileMetadata extends $.Struct {
  static readonly KeyValuePair = FileMetadata_KeyValuePair;
  public static override readonly _capnp = {
    displayName: "FileMetadata",
    id: "8e2cab5d7e28c7b3",
    size: new $.ObjectSize(8, 4),
    defaultType: "normal"
  };
  static _Properties: $.ListCtor<FileMetadata_KeyValuePair>;
  /**
* The type of the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* The output mode of the file.
*
*/
  get type(): string {
    return $.utils.getText(1, this, FileMetadata._capnp.defaultType);
  }
  set type(value: string) {
    $.utils.setText(1, value, this);
  }
  /**
* The timestamp representing the file's creation date.
*
*/
  get mode(): string {
    return $.utils.getText(2, this);
  }
  set mode(value: string) {
    $.utils.setText(2, value, this);
  }
  /**
* Additional metadata associated with the file.
*
*/
  get timestamp(): number {
    return $.utils.getUint32(0, this);
  }
  set timestamp(value: number) {
    $.utils.setUint32(0, value, this);
  }
  _adoptProperties(value: $.Orphan<$.List<FileMetadata_KeyValuePair>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownProperties(): $.Orphan<$.List<FileMetadata_KeyValuePair>> {
    return $.utils.disown(this.properties);
  }
  get properties(): $.List<FileMetadata_KeyValuePair> {
    return $.utils.getList(3, FileMetadata._Properties, this);
  }
  _hasProperties(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initProperties(length: number): $.List<FileMetadata_KeyValuePair> {
    return $.utils.initList(3, FileMetadata._Properties, length, this);
  }
  set properties(value: $.List<FileMetadata_KeyValuePair>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  public override toString(): string { return "FileMetadata_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class ChunkData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "ChunkData",
    id: "84076f13b057f83a",
    size: new $.ObjectSize(8, 4),
  };
  /**
* An additional name for the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* Files that are implicitly loaded after one of the specified files.
*
*/
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptImplicitlyLoadedAfterOneOf(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownImplicitlyLoadedAfterOneOf(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.implicitlyLoadedAfterOneOf);
  }
  /**
* The importer of the file.
*
*/
  get implicitlyLoadedAfterOneOf(): $.List<string> {
    return $.utils.getList(2, $.TextList, this);
  }
  _hasImplicitlyLoadedAfterOneOf(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initImplicitlyLoadedAfterOneOf(length: number): $.List<string> {
    return $.utils.initList(2, $.TextList, length, this);
  }
  set implicitlyLoadedAfterOneOf(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  /**
* The signature preservation mode for the file.
*
*/
  get importer(): string {
    return $.utils.getText(3, this);
  }
  set importer(value: string) {
    $.utils.setText(3, value, this);
  }
  get preserveSignature(): PreserveSignatureType {
    return $.utils.getUint16(0, this) as PreserveSignatureType;
  }
  set preserveSignature(value: PreserveSignatureType) {
    $.utils.setUint16(0, value, this);
  }
  public override toString(): string { return "ChunkData_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class PrebuiltData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "PrebuiltData",
    id: "c5b1a6ca696328ee",
    size: new $.ObjectSize(0, 4),
  };
  /**
* An additional name for the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* The file exports.
*
*/
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  _adoptExports(value: $.Orphan<$.List<string>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownExports(): $.Orphan<$.List<string>> {
    return $.utils.disown(this.exports);
  }
  /**
* The source map for the file.
*
*/
  get exports(): $.List<string> {
    return $.utils.getList(2, $.TextList, this);
  }
  _hasExports(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initExports(length: number): $.List<string> {
    return $.utils.initList(2, $.TextList, length, this);
  }
  set exports(value: $.List<string>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  get map(): string {
    return $.utils.getText(3, this);
  }
  set map(value: string) {
    $.utils.setText(3, value, this);
  }
  public override toString(): string { return "PrebuiltData_" + super.toString(); }
}
/**
* The identifier for the file data.
*
*/
export class AssetData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "AssetData",
    id: "da660c6c1fa4c830",
    size: new $.ObjectSize(8, 3),
  };
  /**
* An additional name for the file.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  /**
* Indicates whether the file needs a code reference.
*
*/
  get name(): string {
    return $.utils.getText(1, this);
  }
  set name(value: string) {
    $.utils.setText(1, value, this);
  }
  /**
* The original file name before any transformations.
*
*/
  get needsCodeReference(): boolean {
    return $.utils.getBit(0, this);
  }
  set needsCodeReference(value: boolean) {
    $.utils.setBit(0, value, this);
  }
  get originalFileName(): string {
    return $.utils.getText(2, this);
  }
  set originalFileName(value: string) {
    $.utils.setText(2, value, this);
  }
  public override toString(): string { return "AssetData_" + super.toString(); }
}
/**
* An identifier for the file.
*
*/
export class FileId extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileId",
    id: "990d6a471072f997",
    size: new $.ObjectSize(0, 2),
  };
  /**
* A virtual (or actual) path to the file in the file system.
*
*/
  get id(): string {
    return $.utils.getText(0, this);
  }
  set id(value: string) {
    $.utils.setText(0, value, this);
  }
  get path(): string {
    return $.utils.getText(1, this);
  }
  set path(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileId_" + super.toString(); }
}
/**
* An identifier for the file.
*
*/
export class FileData extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileData",
    id: "fa6725c8a360f9a2",
    size: new $.ObjectSize(0, 2),
  };
  /**
* A virtual (or actual) path to the file in the file system.
*
*/
  get path(): string {
    return $.utils.getText(0, this);
  }
  set path(value: string) {
    $.utils.setText(0, value, this);
  }
  get code(): string {
    return $.utils.getText(1, this);
  }
  set code(value: string) {
    $.utils.setText(1, value, this);
  }
  public override toString(): string { return "FileData_" + super.toString(); }
}
export class FileSystem extends $.Struct {
  public static override readonly _capnp = {
    displayName: "FileSystem",
    id: "ae0c23d43e56abcf",
    size: new $.ObjectSize(0, 6),
  };
  static _Ids: $.ListCtor<FileId>;
  static _Files: $.ListCtor<FileData>;
  static _Metadata: $.ListCtor<FileMetadata>;
  static _Assets: $.ListCtor<AssetData>;
  static _Chunks: $.ListCtor<ChunkData>;
  static _Prebuilt: $.ListCtor<PrebuiltData>;
  _adoptIds(value: $.Orphan<$.List<FileId>>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownIds(): $.Orphan<$.List<FileId>> {
    return $.utils.disown(this.ids);
  }
  get ids(): $.List<FileId> {
    return $.utils.getList(0, FileSystem._Ids, this);
  }
  _hasIds(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initIds(length: number): $.List<FileId> {
    return $.utils.initList(0, FileSystem._Ids, length, this);
  }
  set ids(value: $.List<FileId>) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  _adoptFiles(value: $.Orphan<$.List<FileData>>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownFiles(): $.Orphan<$.List<FileData>> {
    return $.utils.disown(this.files);
  }
  get files(): $.List<FileData> {
    return $.utils.getList(1, FileSystem._Files, this);
  }
  _hasFiles(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initFiles(length: number): $.List<FileData> {
    return $.utils.initList(1, FileSystem._Files, length, this);
  }
  set files(value: $.List<FileData>) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptMetadata(value: $.Orphan<$.List<FileMetadata>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownMetadata(): $.Orphan<$.List<FileMetadata>> {
    return $.utils.disown(this.metadata);
  }
  get metadata(): $.List<FileMetadata> {
    return $.utils.getList(2, FileSystem._Metadata, this);
  }
  _hasMetadata(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initMetadata(length: number): $.List<FileMetadata> {
    return $.utils.initList(2, FileSystem._Metadata, length, this);
  }
  set metadata(value: $.List<FileMetadata>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  _adoptAssets(value: $.Orphan<$.List<AssetData>>): void {
    $.utils.adopt(value, $.utils.getPointer(3, this));
  }
  _disownAssets(): $.Orphan<$.List<AssetData>> {
    return $.utils.disown(this.assets);
  }
  get assets(): $.List<AssetData> {
    return $.utils.getList(3, FileSystem._Assets, this);
  }
  _hasAssets(): boolean {
    return !$.utils.isNull($.utils.getPointer(3, this));
  }
  _initAssets(length: number): $.List<AssetData> {
    return $.utils.initList(3, FileSystem._Assets, length, this);
  }
  set assets(value: $.List<AssetData>) {
    $.utils.copyFrom(value, $.utils.getPointer(3, this));
  }
  _adoptChunks(value: $.Orphan<$.List<ChunkData>>): void {
    $.utils.adopt(value, $.utils.getPointer(4, this));
  }
  _disownChunks(): $.Orphan<$.List<ChunkData>> {
    return $.utils.disown(this.chunks);
  }
  get chunks(): $.List<ChunkData> {
    return $.utils.getList(4, FileSystem._Chunks, this);
  }
  _hasChunks(): boolean {
    return !$.utils.isNull($.utils.getPointer(4, this));
  }
  _initChunks(length: number): $.List<ChunkData> {
    return $.utils.initList(4, FileSystem._Chunks, length, this);
  }
  set chunks(value: $.List<ChunkData>) {
    $.utils.copyFrom(value, $.utils.getPointer(4, this));
  }
  _adoptPrebuilt(value: $.Orphan<$.List<PrebuiltData>>): void {
    $.utils.adopt(value, $.utils.getPointer(5, this));
  }
  _disownPrebuilt(): $.Orphan<$.List<PrebuiltData>> {
    return $.utils.disown(this.prebuilt);
  }
  get prebuilt(): $.List<PrebuiltData> {
    return $.utils.getList(5, FileSystem._Prebuilt, this);
  }
  _hasPrebuilt(): boolean {
    return !$.utils.isNull($.utils.getPointer(5, this));
  }
  _initPrebuilt(length: number): $.List<PrebuiltData> {
    return $.utils.initList(5, FileSystem._Prebuilt, length, this);
  }
  set prebuilt(value: $.List<PrebuiltData>) {
    $.utils.copyFrom(value, $.utils.getPointer(5, this));
  }
  public override toString(): string { return "FileSystem_" + super.toString(); }
}
FileMetadata._Properties = $.CompositeList(FileMetadata_KeyValuePair);
FileSystem._Ids = $.CompositeList(FileId);
FileSystem._Files = $.CompositeList(FileData);
FileSystem._Metadata = $.CompositeList(FileMetadata);
FileSystem._Assets = $.CompositeList(AssetData);
FileSystem._Chunks = $.CompositeList(ChunkData);
FileSystem._Prebuilt = $.CompositeList(PrebuiltData);
